# Generated by Django 2.2.13 on 2021-09-15 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideBook',
            fields=[
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False, verbose_name='Unique URL-Safe Title')),
            ],
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('header_level', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(max_length=80, verbose_name='URL-Safe Title')),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=74000)),
                ('rendered_content', models.TextField(max_length=78000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='date last edited')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.GuideBook')),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='guidesection',
            index=models.Index(fields=['book', 'slug', 'is_deleted'], name='guide_guide_book_id_d9b278_idx'),
        ),
        migrations.AddIndex(
            model_name='guidesection',
            index=models.Index(fields=['book', 'position', 'is_deleted'], name='guide_guide_book_id_8e92ce_idx'),
        ),
        migrations.AddIndex(
            model_name='guidesection',
            index=models.Index(fields=['position'], name='guide_guide_positio_1e61a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidesection',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('book', 'slug'), name='one_slug_per_book'),
        ),
        migrations.AddConstraint(
            model_name='guidesection',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('book', 'position'), name='one_pos_per_book'),
        ),
    ]
