# Generated by Django 2.2.13 on 2021-10-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20210925_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
