# Generated by Django 2.2.13 on 2021-10-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guidebook_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidesection',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
