# Generated by Django 3.2.9 on 2022-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_guidesection_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePic',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
