# Generated by Django 3.2.15 on 2023-01-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_guidebook_rendered_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='is_under_construction',
            field=models.BooleanField(default=False),
        ),
    ]
