# Generated by Django 3.2.15 on 2023-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_guidebook_is_under_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidesection',
            name='is_spoilers',
            field=models.BooleanField(default=False),
        ),
    ]
