# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('appearance', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=11)),
                ('concept_summary', models.CharField(max_length=150)),
                ('ambition', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('edit_date', models.DateTimeField(verbose_name='date last edited')),
                ('basic_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.BasicStats')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_character', 'View character'), ('edit_character', 'Edit character')),
            },
        ),
    ]
