# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20170704_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'permissions': (('view_character', 'View character'), ('view_private_character', 'View private character'), ('edit_character', 'Edit character'))},
        ),
        migrations.AddField(
            model_name='character',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
