# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20170711_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
