# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='NOVICE', max_length=25),
        ),
    ]
