# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20170829_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicstats',
            name='stats',
            field=models.CharField(max_length=10000),
        ),
    ]
