# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20170906_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicstats',
            name='advancement_history',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='armor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='basicstats',
            name='movement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='contacts',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='contracts',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='current_alias',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_encumbrance',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='paradigm',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='previous_aliases',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='residence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='resources',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='to_do_list',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='total_encumbrance',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='wish_list',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(max_length=15),
        ),
    ]
