# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20170909_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='disabilities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='insanities',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
