# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20170909_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicstats',
            name='advancement_history',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='contracts',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='to_do_list',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
