# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20170910_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_void', models.BooleanField(default=False)),
                ('obituary', models.CharField(blank=True, max_length=10000, null=True)),
                ('date_of_death', models.DateTimeField(verbose_name='date of death')),
                ('cause_of_death', models.CharField(blank=True, max_length=200, null=True)),
                ('relevant_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
    ]
