# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_character_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graveyard_Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
        ),
    ]
