# Generated by Django 2.2.12 on 2020-05-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_graveyard_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'permissions': (('view_private_character', 'View private character'), ('edit_character', 'Edit character'))},
        ),
    ]
