# Generated by Django 2.2.12 on 2020-05-31 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0006_cellinvite_created_date'),
        ('characters', '0013_auto_20200519_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cells.Cell'),
        ),
    ]
