# Generated by Django 2.2.12 on 2020-06-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_character_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tutorialText', models.CharField(blank=True, max_length=250, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbilityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('relevant_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tutorialText', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('relevant_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_values', models.ManyToManyField(blank=True, through='characters.AbilityValue', to='characters.Ability')),
                ('attribute_values', models.ManyToManyField(blank=True, through='characters.AttributeValue', to='characters.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='relevant_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
        migrations.AddField(
            model_name='abilityvalue',
            name='relevant_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
    ]
