# Generated by Django 2.2.12 on 2020-07-11 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0014_character_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tutorial_text', models.CharField(blank=True, max_length=250, null=True)),
                ('is_physical', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbilityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AbilityValue')),
                ('relevant_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('system', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Physical'), ('BACKGROUND', 'Background'), ('MENTAL', 'Mental'), ('RESTRICTED', 'Restricted')], default='BACKGROUND', max_length=50)),
                ('eratta', models.CharField(blank=True, max_length=2500, null=True)),
                ('details_field_name', models.CharField(blank=True, max_length=150, null=True)),
                ('multiplicity_allowed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AssetDetails')),
                ('relevant_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tutorial_text', models.CharField(blank=True, max_length=250, null=True)),
                ('is_physical', models.BooleanField(default=False)),
                ('scales_body', models.BooleanField(default=False)),
                ('scales_mind', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AttributeValue')),
                ('relevant_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_info', models.TextField(max_length=3000)),
                ('attributes', models.TextField(max_length=3000)),
                ('abilities', models.TextField(max_length=3000)),
                ('secondary_abilities', models.TextField(max_length=3000)),
                ('assets_and_liabilities', models.TextField(max_length=3000)),
                ('limits', models.TextField(max_length=3000)),
                ('limits_view', models.TextField(max_length=3000)),
                ('traumas', models.TextField(max_length=3000)),
                ('injuries', models.TextField(max_length=3000)),
                ('battle_scars', models.TextField(max_length=3000)),
                ('penalty', models.TextField(max_length=3000)),
                ('mind', models.TextField(max_length=3000)),
                ('body', models.TextField(max_length=3000)),
                ('source_edit', models.TextField(max_length=3000)),
                ('source_view', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('exp_cost', models.IntegerField(default=-1)),
                ('abilities', models.ManyToManyField(blank=True, through='characters.AbilityValue', to='characters.Ability')),
                ('assets', models.ManyToManyField(blank=True, through='characters.AssetDetails', to='characters.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('system', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Physical'), ('BACKGROUND', 'Background'), ('MENTAL', 'Mental'), ('RESTRICTED', 'Restricted')], default='BACKGROUND', max_length=50)),
                ('eratta', models.CharField(blank=True, max_length=2500, null=True)),
                ('details_field_name', models.CharField(blank=True, max_length=150, null=True)),
                ('multiplicity_allowed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('current_val', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trauma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='mental_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='pronoun',
            field=models.CharField(choices=[('HE', 'his'), ('SHE', 'her'), ('THEY', 'their')], default='THEY', max_length=25),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
        migrations.CreateModel(
            name='TraumaRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('was_bought_off', models.BooleanField(default=False)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.TraumaRevision')),
                ('relevant_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats')),
                ('relevant_trauma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Trauma')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.PositiveIntegerField()),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.SourceRevision')),
                ('relevant_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Source')),
                ('relevant_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.CreateModel(
            name='LimitRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.LimitRevision')),
                ('relevant_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Limit')),
                ('relevant_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats')),
            ],
        ),
        migrations.CreateModel(
            name='LiabilityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.LiabilityDetails')),
                ('relevant_liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Liability')),
                ('relevant_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('severity', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rewarded_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('rewarded_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contractstats',
            name='assigned_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='attributes',
            field=models.ManyToManyField(blank=True, through='characters.AttributeValue', to='characters.Attribute'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='liabilities',
            field=models.ManyToManyField(blank=True, through='characters.LiabilityDetails', to='characters.Liability'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='limits',
            field=models.ManyToManyField(blank=True, through='characters.LimitRevision', to='characters.Limit'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='sources',
            field=models.ManyToManyField(blank=True, through='characters.SourceRevision', to='characters.Source'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='traumas',
            field=models.ManyToManyField(blank=True, through='characters.TraumaRevision', to='characters.Trauma'),
        ),
        migrations.CreateModel(
            name='BattleScar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='relevant_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='relevant_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
        migrations.AddField(
            model_name='abilityvalue',
            name='relevant_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
        migrations.AddField(
            model_name='character',
            name='stats_snapshot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
        migrations.AddIndex(
            model_name='traumarevision',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_1f0cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerevision',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_d8d7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='limitrevision',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_6c3ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='liabilitydetails',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_f983ea_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstats',
            index=models.Index(fields=['assigned_character', 'is_snapshot'], name='stats_char_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstats',
            index=models.Index(fields=['created_time'], name='stats_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_4c5afa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('relevant_attribute', 'relevant_stats')},
        ),
        migrations.AddIndex(
            model_name='assetdetails',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_2746f4_idx'),
        ),
        migrations.AddIndex(
            model_name='abilityvalue',
            index=models.Index(fields=['relevant_stats'], name='characters__relevan_e91f81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='abilityvalue',
            unique_together={('relevant_ability', 'relevant_stats')},
        ),
    ]
