# Generated by Django 2.2.12 on 2020-06-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200616_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('system', models.CharField(max_length=2000)),
                ('eratta', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('system', models.CharField(max_length=2000)),
                ('eratta', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='contractstats',
            old_name='ability_values',
            new_name='abilities',
        ),
        migrations.RenameField(
            model_name='contractstats',
            old_name='attribute_values',
            new_name='attributes',
        ),
        migrations.CreateModel(
            name='MeritDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=2000)),
                ('relevant_merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Merit')),
                ('relevant_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlawDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=2000)),
                ('relevant_flaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Flaw')),
                ('relevant_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contractstats',
            name='flaws',
            field=models.ManyToManyField(blank=True, through='characters.FlawDetails', to='characters.Flaw'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='limits',
            field=models.ManyToManyField(blank=True, to='characters.Limit'),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='merits',
            field=models.ManyToManyField(blank=True, through='characters.MeritDetails', to='characters.Merit'),
        ),
    ]
