# Generated by Django 2.2.12 on 2020-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200711_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='experience_edit',
            field=models.TextField(default='experieince', max_length=3000),
            preserve_default=False,
        ),
    ]
