# Generated by Django 2.2.12 on 2020-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_charactertutorial_experience_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='abilities_view',
            field=models.TextField(default='Abilities represent special training and conditioning. A rating of 1 or higher represents special training. Click to show / hide Primary Abilities with a rating of 0.', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='attributes_view',
            field=models.TextField(default="Attributes descibe your core capabilities. All rolls (besides Mind, Body, and Initiative rolls) are performed by taking an Attribute's rating, an Ability's rating, adding them together, and rolling that many ten-sided dice. Any die that shows the roll's Difficulty rating or higher is counted towards success. Initiative is rolled by adding Dexterity and Wits.", max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='character_timeline',
            field=models.TextField(default='The timeline keeps a log of all the Games you have attended, their outcomes, and how you spent each Gift. It also tracks the edits you make to your stats, and the experience you earn and spend.', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='equipment',
            field=models.TextField(default="Your Equipment is a list of the items you have access to. Different GMs may be more or less strict about this sort of book-keeping, but if it's not listed here, you're relying on the GM's charity if you want to use it.", max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='powers_view',
            field=models.TextField(default='Winning Games grants you a Gift that is used to awaken your potential, resulting in a new Power or an improvement to an existing Power. These Powers mare often unique to the individual, leading to Contractors occasionally being called "snowflakes of carnage"', max_length=3000),
            preserve_default=False,
        ),
    ]
