# Generated by Django 2.2.12 on 2020-06-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20200617_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('BACKGROUND', 'Background'), ('MENTAL', 'Mental'), ('RESTRICTED', 'Veteran')], default='BACKGROUND', max_length=50),
        ),
        migrations.AddField(
            model_name='liability',
            name='category',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('BACKGROUND', 'Background'), ('MENTAL', 'Mental'), ('RESTRICTED', 'Veteran')], default='BACKGROUND', max_length=50),
        ),
    ]
