# Generated by Django 2.2.12 on 2020-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20200617_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.TextField(max_length=3000)),
                ('secondary_abilities', models.TextField(max_length=3000)),
                ('attributes', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('BACKGROUND', 'Background'), ('MENTAL', 'Mental'), ('RESTRICTED', 'Restricted')], default='BACKGROUND', max_length=50),
        ),
        migrations.AlterField(
            model_name='liability',
            name='category',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('BACKGROUND', 'Background'), ('MENTAL', 'Mental'), ('RESTRICTED', 'Restricted')], default='BACKGROUND', max_length=50),
        ),
    ]
