# Generated by Django 2.2.12 on 2020-07-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20200712_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.CharField(blank=True, default="\n## On Person\n\n* Clothes\n* Wallet\n* Keys\n* flask of tears\n* Rugged no-metal belt that can be used as a pair of nunchucks\n\n## In Bag\n\n* Oxygen canister\n* Census-taker's liver\n* Fava Beans\n* Chianti\n", max_length=15000, null=True),
        ),
    ]
