# Generated by Django 2.2.12 on 2020-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_auto_20200618_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='multiplicity_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liability',
            name='multiplicity_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
