# Generated by Django 2.2.12 on 2020-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_auto_20200716_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='charon_coin',
            field=models.TextField(default='A Charon Coin is a token rewarded when you lose a Character in a Game. It can be spent when creating a new Character to award them a free Gift', max_length=3000),
            preserve_default=False,
        ),
    ]
