# Generated by Django 2.2.12 on 2020-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_charactertutorial_assets_and_liabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='core_info',
            field=models.TextField(default='These fields represent your character at a glance. Who are they?', max_length=3000),
            preserve_default=False,
        ),
    ]
