# Generated by Django 2.2.12 on 2020-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_charactertutorial_charon_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
