# Generated by Django 2.2.12 on 2020-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_charactertutorial_core_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='details_field_name',
            field=models.CharField(default='details', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability',
            name='details_field_name',
            field=models.CharField(default='details', max_length=150),
            preserve_default=False,
        ),
    ]
