# Generated by Django 2.2.12 on 2020-09-11 17:09

import characters.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_character_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='edit_secret_key',
            field=models.CharField(default=characters.models.random_string, max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
