# Generated by Django 2.2.12 on 2020-09-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20200911_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='modal_1',
            field=models.TextField(default='def', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='modal_2',
            field=models.TextField(default='def', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='modal_3',
            field=models.TextField(default='def', max_length=3000),
            preserve_default=False,
        ),
    ]
