# Generated by Django 2.2.12 on 2020-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20200619_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='details_field_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='liability',
            name='details_field_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
