# Generated by Django 2.2.12 on 2020-06-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_auto_20200619_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.ContractStats'),
        ),
    ]
