# Generated by Django 2.2.13 on 2020-12-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_auto_20200922_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='grants_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liability',
            name='grants_gift',
            field=models.BooleanField(default=False),
        ),
    ]
