# Generated by Django 2.2.12 on 2020-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_character_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='liabilitydetails',
            name='details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
