# Generated by Django 2.2.13 on 2021-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20201230_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstats',
            name='count_exp_costs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
