# Generated by Django 2.2.13 on 2021-03-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20201230_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mind', models.BooleanField(default=False)),
                ('is_body', models.BooleanField(default=False)),
                ('difficulty', models.PositiveIntegerField(default=6)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Ability')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
            ],
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['is_mind', 'difficulty'], name='characters__is_mind_7d6c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['is_body', 'difficulty'], name='characters__is_body_4269ab_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['attribute', 'ability', 'difficulty'], name='characters__attribu_665a70_idx'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(fields=('attribute', 'ability', 'difficulty', 'is_mind', 'is_body'), name='unique_roll'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(condition=models.Q(is_mind=True), fields=('is_mind', 'difficulty'), name='one_mind_roll'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(condition=models.Q(is_body=True), fields=('is_body', 'difficulty'), name='one_body_roll'),
        ),
    ]
