# Generated by Django 2.2.13 on 2021-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_auto_20210303_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencereward',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
