# Generated by Django 2.2.13 on 2021-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_auto_20210220_1715'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roll',
            name='one_mind_roll',
        ),
        migrations.RemoveConstraint(
            model_name='roll',
            name='one_body_roll',
        ),
        migrations.RemoveIndex(
            model_name='roll',
            name='characters__is_mind_2823fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='roll',
            name='characters__is_body_f5e372_idx',
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['is_mind', 'difficulty'], name='characters__is_mind_7d6c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['is_body', 'difficulty'], name='characters__is_body_4269ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(condition=models.Q(is_mind=True), fields=('is_mind', 'difficulty'), name='one_mind_roll'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(condition=models.Q(is_body=True), fields=('is_body', 'difficulty'), name='one_body_roll'),
        ),
    ]
