# Generated by Django 2.2.12 on 2020-06-24 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from characters.models import Character


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0027_auto_20200622_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='stats',
            new_name='stats_snapshot',
        ),
        migrations.AddField(
            model_name='abilityvalue',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AbilityValue'),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AssetDetails'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AttributeValue'),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='limits',
            field=models.TextField(default='limits help text', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractstats',
            name='assigned_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractstats',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contractstats',
            name='is_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liabilitydetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liabilitydetails',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.LiabilityDetails'),
        ),
        migrations.AlterUniqueTogether(
            name='abilityvalue',
            unique_together={('relevant_ability', 'relevant_stats')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('relevant_attribute', 'relevant_stats')},
        ),
        migrations.CreateModel(
            name='ExperienceReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rewarded_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('rewarded_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
