# Generated by Django 2.2.13 on 2021-03-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_experiencereward_is_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
