# Generated by Django 2.2.12 on 2020-06-24 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20200624_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstats',
            name='assigned_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
    ]
