# Generated by Django 2.2.13 on 2021-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20210317_0407'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roll',
            name='unique_roll',
        ),
        migrations.RemoveConstraint(
            model_name='roll',
            name='one_mind_roll',
        ),
        migrations.RemoveConstraint(
            model_name='roll',
            name='one_body_roll',
        ),
        migrations.AddField(
            model_name='roll',
            name='parry_type',
            field=models.CharField(choices=[('NO_INFO', 'not applicable'), ('UNAVOIDABLE', 'an attack that cannot be dodged or parried'), ('DODGE_ONLY', 'an attack that can only be dodged'), ('UNARMED', 'an unarmed attack'), ('MELEE_EDGED', 'an attack with an edged melee weapon'), ('MELEE_BLUNT', 'an attack with a blunt melee weapon'), ('BOW', 'an attack with a bow or crossbow'), ('THROWN', 'an attack with a thrown weapon'), ('FIREARM', 'an attack with a firearm')], default='NO_INFO', max_length=30),
        ),
        migrations.AddField(
            model_name='roll',
            name='speed',
            field=models.CharField(choices=[('NA', 'not applicable'), ('FREE', 'a free Action'), ('ACTION_QUICK', 'a quick Action'), ('ACTION_SPLITTABLE', 'an Action that may be split'), ('ACTION_COMMITTED', 'a committed Action'), ('REACTION', 'a Reaction')], default='NA', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(fields=('attribute', 'ability', 'difficulty', 'is_mind', 'is_body', 'parry_type', 'speed'), name='unique_roll'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(condition=models.Q(is_mind=True), fields=('is_mind', 'difficulty', 'parry_type', 'speed'), name='one_mind_roll'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(condition=models.Q(is_body=True), fields=('is_body', 'difficulty', 'parry_type', 'speed'), name='one_body_roll'),
        ),
    ]
