# Generated by Django 2.2.13 on 2021-04-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_auto_20210415_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.CharField(blank=True, default='\nTrack your current equipment here. You may start with anything your Contractor would reasonably have access to. \n\n#### On Person\n\n* Jeans\n* T-shirt\n* Wallet\n* Keys\n* Smartphone\n* A pocket knife\n\n#### Purple Jansport backpack\n\n* Rain jacket\n* Metal water bottle\n* Toiletries kit\n', max_length=15000, null=True),
        ),
    ]
