# Generated by Django 2.2.13 on 2021-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_auto_20210426_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='world_modal_1',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='world_modal_2',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='world_modal_3',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
    ]
