# Generated by Django 2.2.13 on 2021-05-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_auto_20210515_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='artifacts',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='circumstances',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='conditions',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
    ]
