# Generated by Django 2.2.13 on 2021-05-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_artifact_circumstance_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.AddIndex(
            model_name='attributebonus',
            index=models.Index(fields=['character', 'attribute'], name='characters__charact_32bb49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributebonus',
            unique_together={('character', 'attribute')},
        ),
    ]
