# Generated by Django 2.2.13 on 2021-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0037_experiencereward_custom_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencereward',
            name='custom_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
