# Generated by Django 2.2.13 on 2021-07-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_experiencereward_custom_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='wound',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
    ]
