# Generated by Django 2.2.13 on 2021-09-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0040_auto_20210730_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='encumbrance',
            field=models.TextField(default='placeholder', max_length=3000),
        ),
    ]
