# Generated by Django 2.2.13 on 2021-09-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0041_charactertutorial_encumbrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='num_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='num_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='num_victories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
