# Generated by Django 2.2.13 on 2021-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0044_auto_20210905_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='num_journals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['num_journals'], name='characters__num_jou_649a20_idx'),
        ),
    ]
