# Generated by Django 2.2.13 on 2021-09-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0047_auto_20210909_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='num_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='num_journals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='num_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='num_victories',
            field=models.IntegerField(default=0),
        ),
    ]
