# Generated by Django 2.2.13 on 2021-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0052_exp_reward_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencereward',
            name='type',
            field=models.CharField(choices=[('MVP', 'earning MVP'), ('LOSS_V1', 'losing'), ('LOSS_RINGER_V1', 'losing as a ringer'), ('WIN_V1', 'winning'), ('WIN_RINGER_V1', 'winning as a ringer'), ('LOSS_V2', 'losing'), ('LOSS_IN_WORLD_V2', 'losing in-World Contract'), ('LOSS_RINGER_V2', 'losing as a ringer'), ('WIN_V2', 'winning'), ('WIN_IN_WORLD_V2', 'winning in-World Contract'), ('WIN_RINGER_V2', 'winning as a ringer'), ('GM', 'GMing'), ('JOURNAL', 'writing a journal'), ('CUSTOM', 'custom reason')], default='MVP', max_length=45),
        ),
    ]
