# Generated by Django 2.2.13 on 2021-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0053_auto_20211114_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
