# Generated by Django 3.2.9 on 2022-01-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0057_auto_20220119_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MELEE', 'Melee Weapon'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', max_length=30)),
                ('bonus_damage', models.IntegerField(default=0)),
                ('damage_errata', models.CharField(blank=True, max_length=300)),
                ('attack_roll_text', models.CharField(blank=True, max_length=300)),
                ('range', models.CharField(blank=True, max_length=300)),
                ('errata', models.CharField(blank=True, max_length=300)),
                ('attack_roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.roll')),
            ],
        ),
    ]
