# Generated by Django 3.2.9 on 2022-02-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0058_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('MELEE', 'Melee'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', max_length=30),
        ),
    ]
