# Generated by Django 3.2.9 on 2022-02-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0060_weapon_attack_system_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('MELEE', 'Melee'), ('UNARMED', 'Unarmed'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', max_length=30),
        ),
    ]
