# Generated by Django 3.2.9 on 2022-02-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0062_injury_is_stabilized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbattlescar',
            name='type',
            field=models.CharField(choices=[('1MINOR', 'Minor Scars (Severity 4)'), ('2MAJOR', 'Major Scars (Severity 5)'), ('3SEVERE', 'Severe Scars (Severity 6)'), ('4EXTREME', 'Extreme Scars (Severity 7+)')], default='1MINOR', max_length=45),
        ),
    ]
