# Generated by Django 3.2.9 on 2022-03-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0063_alter_stockbattlescar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOST', 'Lost'), ('DESTROYED', 'Destroyed'), ('BROKEN', 'Needs repair')], default='AVAILABLE', max_length=55),
        ),
        migrations.AddField(
            model_name='artifact',
            name='crafting_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='characters.character'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='is_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='artifact',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='system',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='circumstance',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='circumstance',
            name='system',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='system',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
