# Generated by Django 3.2.9 on 2022-04-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0066_auto_20220328_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=5000)),
                ('status_change_type', models.CharField(choices=[('LOST', 'lost'), ('RECOVERED', 'recovered'), ('DESTROYED', 'destroyed'), ('REPAIRED', 'repaired')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactTransferEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=5000)),
                ('transfer_type', models.CharField(choices=[('GIVEN', 'given to'), ('STOLEN', 'stolen by'), ('LOOTED', 'looted by')], max_length=55)),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='availability',
        ),
        migrations.AddField(
            model_name='artifact',
            name='most_recent_status_change',
            field=models.CharField(blank=True, choices=[('LOST', 'lost'), ('RECOVERED', 'recovered'), ('DESTROYED', 'destroyed'), ('REPAIRED', 'repaired')], max_length=55),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['crafting_character'], name='characters__craftin_f471f1_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['creating_player'], name='characters__creatin_992919_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['character'], name='characters__charact_ff55ec_idx'),
        ),
        migrations.AddField(
            model_name='artifacttransferevent',
            name='from_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_artifact_status', to='characters.character'),
        ),
        migrations.AddField(
            model_name='artifacttransferevent',
            name='relevant_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.artifact'),
        ),
        migrations.AddField(
            model_name='artifacttransferevent',
            name='to_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_artifact_status', to='characters.character'),
        ),
        migrations.AddField(
            model_name='artifactstatuschange',
            name='relevant_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.artifact'),
        ),
        migrations.AddIndex(
            model_name='artifacttransferevent',
            index=models.Index(fields=['relevant_artifact', 'created_time'], name='characters__relevan_fd05e0_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactstatuschange',
            index=models.Index(fields=['relevant_artifact', 'created_time'], name='characters__relevan_2d2b5c_idx'),
        ),
    ]
