# Generated by Django 3.2.9 on 2022-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0067_auto_20220408_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='is_crafted_artifact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='since_revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifactstatuschange',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='artifacttransferevent',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='crafting_avail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='highlight_crafting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circumstance',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='circumstance',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circumstance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condition',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='most_recent_status_change',
            field=models.CharField(blank=True, choices=[('LOST', 'Lost'), ('RECOVERED', 'Recovered'), ('DESTROYED', 'Destroyed'), ('REPAIRED', 'Repaired'), ('ATHOME', 'At home')], max_length=55),
        ),
        migrations.AlterField(
            model_name='artifactstatuschange',
            name='status_change_type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('RECOVERED', 'Recovered'), ('DESTROYED', 'Destroyed'), ('REPAIRED', 'Repaired'), ('ATHOME', 'At home')], max_length=55),
        ),
    ]
