# Generated by Django 3.2.9 on 2022-07-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0069_auto_20220630_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbattlescar',
            name='type',
            field=models.CharField(choices=[('1MINOR', 'Minor Scars (Severity 4)'), ('2MAJOR', 'Major Scars (Severity 5)'), ('3SEVERE', 'Severe Scars (Severity 6)'), ('4EXTREME', 'Extreme Scars (Severity 7+)'), ('5STARTONLY', 'Asset and Liability Scars')], default='1MINOR', max_length=45),
        ),
    ]
