# Generated by Django 3.2.9 on 2022-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0071_auto_20220709_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='grants_non_stock_element',
            field=models.CharField(blank=True, choices=[('Condition', 'Condition'), ('Circumstance', 'Circumstance'), ('Trophy', 'Trophy'), ('Trauma', 'Trauma'), ('Battle Scar', 'Battle Scar')], help_text="Grants world element that isn't stock. Don't set if using one of the stock world elements.", max_length=55),
        ),
        migrations.AlterField(
            model_name='liability',
            name='grants_non_stock_element',
            field=models.CharField(blank=True, choices=[('Condition', 'Condition'), ('Circumstance', 'Circumstance'), ('Trophy', 'Trophy'), ('Trauma', 'Trauma'), ('Battle Scar', 'Battle Scar')], help_text="Grants world element that isn't stock. Don't set if using one of the stock world elements.", max_length=55),
        ),
    ]
