# Generated by Django 3.2.9 on 2022-07-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0015_auto_20220514_1620'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0073_alter_experiencereward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockworldelement',
            name='cutoff',
            field=models.PositiveIntegerField(default=1, verbose_name='cutoff (for loose ends)'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='system',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='asset',
            name='grants_non_stock_element',
            field=models.CharField(blank=True, choices=[('Condition', 'Condition'), ('Circumstance', 'Circumstance'), ('Trophy', 'Trophy'), ('Trauma', 'Trauma'), ('Battle Scar', 'Battle Scar'), ('Loose End', 'Loose End')], help_text="Grants world element that isn't stock. Don't set if using one of the stock world elements.", max_length=55),
        ),
        migrations.AlterField(
            model_name='circumstance',
            name='system',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='system',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='liability',
            name='grants_non_stock_element',
            field=models.CharField(blank=True, choices=[('Condition', 'Condition'), ('Circumstance', 'Circumstance'), ('Trophy', 'Trophy'), ('Trauma', 'Trauma'), ('Battle Scar', 'Battle Scar'), ('Loose End', 'Loose End')], help_text="Grants world element that isn't stock. Don't set if using one of the stock world elements.", max_length=55),
        ),
        migrations.AlterField(
            model_name='stockworldelement',
            name='type',
            field=models.CharField(choices=[('Condition', 'Condition'), ('Circumstance', 'Circumstance'), ('Trophy', 'Trophy'), ('Trauma', 'Trauma'), ('Loose End', 'Loose End')], default='Condition', max_length=45),
        ),
        migrations.CreateModel(
            name='LooseEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('origin', models.CharField(blank=True, max_length=2000)),
                ('system', models.CharField(blank=True, max_length=5000)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=5000)),
                ('cutoff', models.PositiveIntegerField(default=1)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cells.cell')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('granting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
