# Generated by Django 3.2.9 on 2022-07-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0075_auto_20220723_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='looseend',
            name='threat_level',
            field=models.CharField(choices=[('1DANGEROUS', 'Dangerous'), ('3DEADLY', 'Deadly'), ('5FATEFUL', 'Fateful')], default='1DANGEROUS', max_length=45),
        ),
    ]
