# Generated by Django 3.2.9 on 2022-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0078_stockworldelement_how_to_tie_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockworldelement',
            name='threat_level',
            field=models.CharField(choices=[('1DANGEROUS', 'Dangerous'), ('3DEADLY', 'Deadly'), ('5FATEFUL', 'Fateful')], default='1DANGEROUS', help_text='for loose ends only', max_length=45),
        ),
    ]
