# Generated by Django 3.2.9 on 2022-07-29 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0079_stockworldelement_threat_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='looseend',
            name='granting_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
