# Generated by Django 3.2.15 on 2022-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0081_auto_20220802_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='archetypes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='professions',
            field=models.JSONField(default=list),
        ),
    ]
