# Generated by Django 3.2.15 on 2022-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0082_auto_20220924_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertutorial',
            name='paradigms',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactertutorial',
            name='personality_traits',
            field=models.JSONField(default=list),
        ),
    ]
