# Generated by Django 3.2.15 on 2022-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0084_charactertutorial_ambitions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['player', 'cell'], name='characters__player__0b6fbb_idx'),
        ),
    ]
