# Generated by Django 3.2.15 on 2022-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0085_character_characters__player__0b6fbb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
