# Generated by Django 3.2.15 on 2022-10-05 13:57

from django.db import migrations

def migrate_denormalize_death(apps, schema_editor):
    Character = apps.get_model('characters', 'Character')
    for character in Character.objects.all():
        character.is_dead = character.character_death_set.filter(is_void=False).exists()
        character.save()


def reverse_migrate_denormralize_death(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0086_character_is_dead'),
    ]

    operations = [
        migrations.RunPython(migrate_denormalize_death, reverse_migrate_denormralize_death),
    ]
