# Generated by Django 3.2.15 on 2022-10-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0087_denormalize_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='relevant_circumstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.circumstance'),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='relevant_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.condition'),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='relevant_loose_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.looseend'),
        ),
        migrations.AddField(
            model_name='liabilitydetails',
            name='relevant_circumstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.circumstance'),
        ),
        migrations.AddField(
            model_name='liabilitydetails',
            name='relevant_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.condition'),
        ),
        migrations.AddField(
            model_name='liabilitydetails',
            name='relevant_loose_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.looseend'),
        ),
    ]
