# Generated by Django 3.2.15 on 2022-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0088_auto_20221018_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='deleted_by_quirk_removal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='circumstance',
            name='deleted_by_quirk_removal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='deleted_by_quirk_removal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='looseend',
            name='deleted_by_quirk_removal',
            field=models.BooleanField(default=True),
        ),
    ]
