# Generated by Django 3.2.15 on 2022-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0090_alter_experiencereward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockworldelement',
            name='is_user_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='stockworldelement',
            index=models.Index(fields=['is_user_created'], name='characters__is_user_3c6efa_idx'),
        ),
    ]
