# Generated by Django 3.2.15 on 2023-01-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0091_auto_20221206_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('MELEE', 'Melee'), ('UNARMED', 'Unarmed'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('THROWN_2', 'Thrown other'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', max_length=30),
        ),
    ]
