# Generated by Django 3.2.15 on 2023-01-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0092_alter_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='battlescar',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='battlescar',
            name='system',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='circumstance',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='looseend',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='name',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
