# Generated by Django 3.2.15 on 2023-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0093_auto_20230123_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='started_supernatural',
            field=models.BooleanField(default=False),
        ),
    ]
