# Generated by Django 3.2.15 on 2023-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0096_sourcerevision_refill_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
    ]
