# Generated by Django 3.2.15 on 2023-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0099_auto_20230611_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencereward',
            name='type',
            field=models.CharField(choices=[('MVP', 'earning Commission'), ('LOSS_V1', 'losing'), ('LOSS_RINGER_V1', 'losing as a ringer'), ('WIN_V1', 'winning'), ('WIN_RINGER_V1', 'winning as a ringer'), ('LOSS_V2', 'losing'), ('LOSS_IN_WORLD_V2', 'losing in-World Contract'), ('LOSS_RINGER_V2', 'losing as a ringer'), ('WIN_V2', 'winning'), ('WIN_IN_WORLD_V2', 'winning in-World Contract'), ('WIN_RINGER_V2', 'winning as a ringer'), ('GM', 'GMing'), ('GM_GOLDEN_RATIO', 'GMing and achieving the Golden Ratio'), ('GM_NEW_PLAYER', 'GMing for a new Player'), ('GM_MOVE', 'GMing a Move'), ('JOURNAL', 'writing a journal'), ('CUSTOM', 'custom reason'), ('Exchange', 'submitting a Scenario to the exchange')], default='MVP', max_length=45),
        ),
    ]
