# Generated by Django 3.2.18 on 2023-11-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0101_alter_experiencereward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_stock',
            field=models.BooleanField(default=False),
        ),
    ]
