# Generated by Django 3.2.15 on 2022-10-05 13:57

from django.db import migrations

STATUS_ANY = 'ANY'
STATUS_NEWBIE = 'NEWBIE'
STATUS_NOVICE = 'NOVICE'
STATUS_SEASONED = 'SEASONED'
STATUS_PROFESSIONAL = 'PROFESSIONAL'
STATUS_VETERAN = 'VETERAN'


def migrate_delete_empty_artifacts(apps, schema_editor):
    Artifact = apps.get_model('characters', 'Artifact')
    for artifact in Artifact.objects.filter(is_signature=True).all():
        if artifact.power_full_set.count() == 0:
            print("deleting {}".format(artifact.pk))
            artifact.delete()
    print("Done")

def reverse_migrate_delete_empty_artifacts(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0102_character_is_stock'),
    ]

    operations = [
        migrations.RunPython(migrate_delete_empty_artifacts, reverse_migrate_delete_empty_artifacts),
    ]
