# Generated by Django 3.2.18 on 2023-12-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20231123_1524'),
        ('characters', '0104_alter_experiencereward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='primary_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_image', to='images.privateuserimage'),
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('relevant_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.privateuserimage')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='images',
            field=models.ManyToManyField(through='characters.CharacterImage', to='images.PrivateUserImage'),
        ),
        migrations.AddIndex(
            model_name='characterimage',
            index=models.Index(fields=['relevant_character'], name='characters__relevan_3a3eab_idx'),
        ),
        migrations.AddIndex(
            model_name='characterimage',
            index=models.Index(fields=['relevant_image'], name='characters__relevan_b4f767_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='characterimage',
            unique_together={('relevant_image', 'relevant_character')},
        ),
    ]
