# Generated by Django 4.2.9 on 2025-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0109_alter_experiencereward_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='circumstance',
            index=models.Index(fields=['character'], name='characters__charact_b2fe61_idx'),
        ),
        migrations.AddIndex(
            model_name='condition',
            index=models.Index(fields=['character'], name='characters__charact_0089a6_idx'),
        ),
        migrations.AddIndex(
            model_name='looseend',
            index=models.Index(fields=['character'], name='characters__charact_64602d_idx'),
        ),
    ]
