# Generated by Django 4.2.9 on 2025-08-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0110_experiencereward_source_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('blurb', models.CharField(max_length=10000, null=True)),
                ('relevant_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
