# Generated by Django 4.2.9 on 2025-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0110_circumstance_characters__charact_b2fe61_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='circumstance',
            index=models.Index(fields=['character', 'is_deleted'], name='characters__charact_259158_idx'),
        ),
        migrations.AddIndex(
            model_name='condition',
            index=models.Index(fields=['character', 'is_deleted'], name='characters__charact_bd528c_idx'),
        ),
        migrations.AddIndex(
            model_name='looseend',
            index=models.Index(fields=['character', 'is_deleted'], name='characters__charact_6b152a_idx'),
        ),
    ]
