# Generated by Django 4.2.9 on 2025-11-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0111_charactertimelineevent'),
        ('characters', '0111_circumstance_characters__charact_259158_idx_and_more'),
    ]

    operations = [
    ]
