# Generated by Django 3.2.15 on 2023-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('relevant_character', 'game_attendance', 'question'), name='unique_answer'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('relevant_character', 'written_contract_number', 'question'), name='unique_answer_2'),
        ),
    ]
