# Generated by Django 3.2.15 on 2023-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_answer_game_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
