# Generated by Django 3.2.15 on 2022-11-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
                ('file_size', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['uploader'], name='images_user_uploade_0d0c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['uploader', 'file_size'], name='images_user_uploade_5fcbef_idx'),
        ),
    ]
