# Generated by Django 3.2.15 on 2023-01-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0054_scenario_discovery_is_aftermath_spoiled'),
        ('images', '0002_alter_userimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.scenario'),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['scenario'], name='images_user_scenari_fe23eb_idx'),
        ),
    ]
