# Generated by Django 3.2.18 on 2023-10-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0060_reward_is_questionnaire'),
        ('images', '0003_auto_20230121_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.scenario'),
        ),
    ]
