# Generated by Django 3.2.18 on 2023-11-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0004_alter_userimage_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateUserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.image_upload_name)),
                ('thumbnail', models.ImageField(null=True, upload_to=images.models.image_upload_name)),
                ('file_size', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='userimage',
            name='images_user_scenari_fe23eb_idx',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='scenario',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['scenario'], name='images_user_scenari_fb9c47_idx'),
        ),
        migrations.AddField(
            model_name='privateuserimage',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='privateuserimage',
            index=models.Index(fields=['uploader'], name='images_priv_uploade_58508c_idx'),
        ),
        migrations.AddIndex(
            model_name='privateuserimage',
            index=models.Index(fields=['uploader', 'file_size'], name='images_priv_uploade_032d4c_idx'),
        ),
    ]
