# Generated by Django 3.2.20 on 2024-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20231123_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateuserimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
