# Generated by Django 3.2.20 on 2024-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_manual_image_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateuserimage',
            name='image_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='image_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='thumbnail_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='thumbnail_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
