# Generated by Django 3.2.20 on 2024-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20240426_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateuserimage',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='thumbnail_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='thumbnail_width',
            field=models.IntegerField(default=0),
        ),
    ]
