# Generated by Django 4.2.8 on 2025-05-04 18:18

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_manual_image_dimensions_take_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateuserimage',
            name='image',
            field=models.ImageField(storage=images.models.select_private_storage, upload_to=images.models.image_upload_name),
        ),
        migrations.AlterField(
            model_name='privateuserimage',
            name='thumbnail',
            field=models.ImageField(null=True, storage=images.models.select_private_storage, upload_to=images.models.image_upload_name),
        ),
    ]
