# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Power',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('summary', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('eratta', models.TextField(blank=True, null=True)),
                ('default_activation_style', models.CharField(choices=[('PASSIVE', 'Passive'), ('ACTIVE', 'Active')], default=('PASSIVE', 'Passive'), max_length=25)),
                ('required_status', models.CharField(choices=[('ANY', 'Any'), ('NOVEICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Base_Power_Category',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25, primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Base_Power_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_system', models.CharField(choices=[('ALL', 'All'), ('HOUSEGAMES15', 'House Games 1.5')], default=('HOUSEGAMES15', 'House Games 1.5'), max_length=25)),
                ('system_text', models.TextField()),
                ('eratta', models.TextField(blank=True, null=True)),
                ('base_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power')),
            ],
        ),
        migrations.CreateModel(
            name='Drawback',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('required_status', models.CharField(choices=[('ANY', 'Any'), ('NOVEICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25)),
                ('system', models.CharField(choices=[('ALL', 'All'), ('HOUSEGAMES15', 'House Games 1.5')], default=('ALL', 'All'), max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('eratta', models.TextField(blank=True, null=True)),
                ('multiplicity_allowed', models.BooleanField(default=False)),
                ('detail_field_label', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drawback_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
                ('relevant_drawback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Drawback')),
            ],
        ),
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('required_status', models.CharField(choices=[('ANY', 'Any'), ('NOVEICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25)),
                ('system', models.CharField(choices=[('ALL', 'All'), ('HOUSEGAMES15', 'House Games 1.5')], default=('ALL', 'All'), max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('eratta', models.TextField(blank=True, null=True)),
                ('multiplicity_allowed', models.BooleanField(default=False)),
                ('detail_field_label', models.CharField(blank=True, max_length=35, null=True)),
                ('required_Enhancements', models.ManyToManyField(blank=True, to='powers.Enhancement')),
                ('required_drawbacks', models.ManyToManyField(blank=True, to='powers.Drawback')),
            ],
        ),
        migrations.CreateModel(
            name='Enhancement_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
                ('relevant_enhancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Enhancement')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('level_zero', models.CharField(max_length=60)),
                ('level_one', models.CharField(max_length=60)),
                ('level_two', models.CharField(max_length=60)),
                ('level_three', models.CharField(max_length=60)),
                ('level_four', models.CharField(max_length=60)),
                ('level_five', models.CharField(max_length=60)),
                ('level_six', models.CharField(max_length=60)),
                ('eratta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavor_text', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=2000)),
                ('dice_system', models.CharField(choices=[('ALL', 'All'), ('HOUSEGAMES15', 'House Games 1.5')], max_length=25)),
                ('activation_style', models.CharField(choices=[('PASSIVE', 'Passive'), ('ACTIVE', 'Active')], max_length=25)),
                ('system', models.TextField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power')),
                ('linked_powers', models.ManyToManyField(blank=True, to='powers.Power')),
            ],
        ),
        migrations.CreateModel(
            name='Power_Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasoned', models.IntegerField(verbose_name='Seasoned Threshold')),
                ('veteran', models.IntegerField(verbose_name='Veteran Threshold')),
                ('default', models.IntegerField(verbose_name='Default Level')),
                ('relevant_base_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power')),
                ('relevant_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='power',
            name='parameter_values',
            field=models.ManyToManyField(through='powers.Parameter_Value', to='powers.Power_Param'),
        ),
        migrations.AddField(
            model_name='power',
            name='selected_drawbacks',
            field=models.ManyToManyField(blank=True, through='powers.Drawback_Instance', to='powers.Drawback'),
        ),
        migrations.AddField(
            model_name='power',
            name='selected_enhancements',
            field=models.ManyToManyField(blank=True, through='powers.Enhancement_Instance', to='powers.Enhancement'),
        ),
        migrations.AddField(
            model_name='parameter_value',
            name='relevant_power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power'),
        ),
        migrations.AddField(
            model_name='parameter_value',
            name='relevant_power_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power_Param'),
        ),
        migrations.AddField(
            model_name='enhancement_instance',
            name='relevant_power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power'),
        ),
        migrations.AddField(
            model_name='drawback_instance',
            name='relevant_power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power'),
        ),
        migrations.AddField(
            model_name='drawback',
            name='required_Enhancements',
            field=models.ManyToManyField(blank=True, to='powers.Enhancement'),
        ),
        migrations.AddField(
            model_name='drawback',
            name='required_drawbacks',
            field=models.ManyToManyField(blank=True, to='powers.Drawback'),
        ),
        migrations.AddField(
            model_name='base_power',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power_Category'),
        ),
        migrations.AddField(
            model_name='base_power',
            name='drawbacks',
            field=models.ManyToManyField(to='powers.Drawback'),
        ),
        migrations.AddField(
            model_name='base_power',
            name='enhancements',
            field=models.ManyToManyField(to='powers.Enhancement'),
        ),
        migrations.AddField(
            model_name='base_power',
            name='example_powers',
            field=models.ManyToManyField(blank=True, to='powers.Power'),
        ),
        migrations.AddField(
            model_name='base_power',
            name='parameters',
            field=models.ManyToManyField(through='powers.Power_Param', to='powers.Parameter'),
        ),
        migrations.AlterUniqueTogether(
            name='power_param',
            unique_together=set([('relevant_parameter', 'relevant_base_power')]),
        ),
        migrations.AlterUniqueTogether(
            name='base_power_system',
            unique_together=set([('base_power', 'dice_system')]),
        ),
    ]
