# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
