# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0002_auto_20161215_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_power',
            name='num_free_enhancements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drawback',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
