# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0003_auto_20161219_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25),
        ),
    ]
