# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0004_auto_20170114_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='level_five',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='level_four',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='level_one',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='level_six',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='level_three',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='level_two',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
