# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powers', '0005_auto_20170514_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power_Full',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dice_system', models.CharField(choices=[('ALL', 'All'), ('HOUSEGAMES15', 'House Games 1.5')], max_length=25)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Power_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_power', to='powers.Power_Full')),
                ('parent_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_power', to='powers.Power_Full')),
            ],
        ),
        migrations.AddField(
            model_name='power',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='power',
            name='creation_reason',
            field=models.CharField(choices=[('NEW', 'New'), ('IMPROVEMENT', 'Improvement'), ('REVISION', 'Revision'), ('ADJUSTMENT', 'Adjustment')], default='NEW', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power',
            name='creation_reason_expanded_text',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='base_power',
            name='example_powers',
            field=models.ManyToManyField(blank=True, to='powers.Power_Full'),
        ),
        migrations.AddField(
            model_name='power_full',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power'),
        ),
        migrations.AddField(
            model_name='power_full',
            name='linked_powers',
            field=models.ManyToManyField(blank=True, through='powers.Power_Link', to='powers.Power_Full'),
        ),
        migrations.AddField(
            model_name='power_full',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='power',
            name='parent_power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='powers.Power_Full'),
        ),
    ]
