# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-03 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0006_auto_20170625_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'permissions': (('view_power', 'View power'),)},
        ),
        migrations.AlterModelOptions(
            name='power_full',
            options={'permissions': (('view_power_full', 'View power full'),)},
        ),
    ]
