# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20170704_0804'),
        ('powers', '0008_auto_20170703_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_full',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
    ]
