# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0009_power_full_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'permissions': (('view_power', 'View power'), ('view_private_power', 'View private power'))},
        ),
        migrations.AlterModelOptions(
            name='power_full',
            options={'permissions': (('view_power_full', 'View power full'), ('view_private_power_full', 'View private power full'), ('edit_power_full', 'Edit power full'))},
        ),
        migrations.AddField(
            model_name='power',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='power_full',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
