# Generated by Django 2.2.12 on 2020-05-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0010_auto_20170711_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'permissions': (('view_private_power', 'View private power'),)},
        ),
        migrations.AlterModelOptions(
            name='power_full',
            options={'permissions': (('view_private_power_full', 'View private power full'), ('edit_power_full', 'Edit power full'))},
        ),
        migrations.AlterField(
            model_name='base_power',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='powers.Base_Power_Category'),
        ),
        migrations.AlterField(
            model_name='base_power_system',
            name='base_power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='powers.Base_Power'),
        ),
        migrations.AlterField(
            model_name='enhancement_instance',
            name='relevant_enhancement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='powers.Enhancement'),
        ),
        migrations.AlterField(
            model_name='power_full',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='powers.Base_Power'),
        ),
    ]
