# Generated by Django 2.2.12 on 2020-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0011_auto_20200519_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default=('ANY', 'Any'), max_length=25),
        ),
    ]
