# Generated by Django 2.2.12 on 2020-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0012_auto_20200701_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_full',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
