# Generated by Django 2.2.12 on 2020-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0013_power_full_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerTag',
            fields=[
                ('tag', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
            ],
        ),
        migrations.CreateModel(
            name='PremadeCategory',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('description', models.CharField(max_length=5000)),
                ('is_generic', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(blank=True, to='powers.PowerTag')),
            ],
        ),
        migrations.AddField(
            model_name='power_full',
            name='tags',
            field=models.ManyToManyField(blank=True, to='powers.PowerTag'),
        ),
    ]
