# Generated by Django 2.2.12 on 2020-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0015_remove_base_power_example_powers'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_full',
            name='example_description',
            field=models.CharField(default='', max_length=9000),
            preserve_default=False,
        ),
    ]
