# Generated by Django 2.2.12 on 2020-08-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0016_power_full_example_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_full',
            name='example_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
