# Generated by Django 2.2.13 on 2020-12-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0017_auto_20200803_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_base', models.TextField(max_length=3000)),
                ('modal_edit', models.TextField(max_length=3000)),
            ],
        ),
    ]
