# Generated by Django 2.2.13 on 2020-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0018_powertutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powertutorial',
            name='modal_base_header',
            field=models.TextField(default=' blah', max_length=3000),
            preserve_default=False,
        ),
    ]
