# Generated by Django 2.2.13 on 2021-02-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20201230_2224'),
        ('powers', '0020_powertutorial_modal_edit_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_roll', models.BooleanField(default=False)),
                ('allow_mind', models.BooleanField(default=False)),
                ('allow_body', models.BooleanField(default=False)),
                ('base_power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power_System')),
                ('required_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
            ],
            options={
                'unique_together': {('base_power_system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('chosen_ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Ability')),
                ('chosen_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
                ('relevant_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.SystemField')),
                ('relevant_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power')),
            ],
            options={
                'unique_together': {('relevant_field', 'relevant_power')},
            },
        ),
    ]
