# Generated by Django 2.2.13 on 2021-03-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_auto_20210303_1925'),
        ('powers', '0020_powertutorial_modal_edit_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFieldRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eratta', models.CharField(blank=True, max_length=1000, null=True)),
                ('allow_mind', models.BooleanField(default=False)),
                ('allow_body', models.BooleanField(default=False)),
                ('allow_std_roll', models.BooleanField(default=True)),
                ('difficulty', models.PositiveIntegerField(blank=True, null=True)),
                ('base_power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power_System')),
                ('required_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Attribute')),
            ],
            options={
                'abstract': False,
                'unique_together': {('base_power_system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemFieldText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eratta', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Base_Power_System')),
            ],
            options={
                'abstract': False,
                'unique_together': {('base_power_system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemFieldTextInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('relevant_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.SystemFieldText')),
                ('relevant_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power')),
            ],
            options={
                'unique_together': {('relevant_field', 'relevant_power')},
            },
        ),
        migrations.CreateModel(
            name='SystemFieldRollInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.SystemFieldRoll')),
                ('relevant_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Power')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Roll')),
            ],
            options={
                'unique_together': {('relevant_field', 'relevant_power')},
            },
        ),
    ]
