# Generated by Django 2.2.13 on 2021-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0021_systemfieldroll_systemfieldrollinstance_systemfieldtext_systemfieldtextinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfieldroll',
            name='allow_std_roll',
            field=models.BooleanField(default=True),
        ),
    ]
