# Generated by Django 2.2.13 on 2021-03-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0022_auto_20210303_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='system',
            field=models.TextField(blank=True, max_length=9000, null=True),
        ),
    ]
