# Generated by Django 2.2.13 on 2021-03-14 21:44

from django.db import migrations
from django.db import transaction


def resave_powers(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Power = apps.get_model('powers', 'Power')
    Base_Power_System = apps.get_model('powers', 'Base_Power_System')
    print("starting migration")
    num_systems_nullified = 0
    for power in Power.objects.all():
        with transaction.atomic():
            if hasattr(power, "system") and power.system:
                base_system = Base_Power_System.objects.filter(dice_system="HOUSEGAMES15").get(base_power=power.base)
                if power.system == base_system.system_text:
                    power.system = None
                    power.save()
                    print("nullifying system")
                    num_systems_nullified = num_systems_nullified + 1
    print("total systems nullified: " + str(num_systems_nullified))

class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0023_auto_20210314_2123'),
    ]

    operations = [
        migrations.RunPython(resave_powers),
    ]

