# Generated by Django 2.2.13 on 2021-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0024_auto_20210314_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfieldroll',
            name='allow_parry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemfieldroll',
            name='parry_type',
            field=models.CharField(choices=[('NO_INFO', 'not applicable'), ('UNAVOIDABLE', 'an attack that cannot be dodged or parried'), ('DODGE_ONLY', 'an attack that can only be dodged'), ('UNARMED', 'an unarmed attack'), ('MELEE_EDGED', 'an attack with an edged melee weapon'), ('MELEE_BLUNT', 'an attack with a blunt melee weapon'), ('BOW', 'an attack with a bow or crossbow'), ('THROWN', 'an attack with a thrown weapon'), ('FIREARM', 'an attack with a firearm')], default='THROWN', max_length=30),
        ),
        migrations.AddField(
            model_name='systemfieldroll',
            name='speed',
            field=models.CharField(choices=[('NA', 'not applicable'), ('FREE', 'a free Action'), ('ACTION_QUICK', 'a quick Action'), ('ACTION_SPLITTABLE', 'an Action that may be split'), ('ACTION_COMMITTED', 'a committed Action'), ('REACTION', 'a Reaction')], default='NA', max_length=30),
        ),
    ]
