# Generated by Django 2.2.13 on 2021-04-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0026_auto_20210415_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_power_system',
            name='default_description_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
