# Generated by Django 3.2.9 on 2021-12-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0031_ps2_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power',
            name='allowed_modalities',
            field=models.ManyToManyField(blank=True, help_text='Set on Effects only. Ignored on Vectors and Modalities.', related_name='vector_modalities', to='powers.Base_Power'),
        ),
        migrations.AlterField(
            model_name='base_power',
            name='allowed_vectors',
            field=models.ManyToManyField(blank=True, help_text='Set on Effects and Modalities only. Ignored on Vectors.', related_name='vector_effects', to='powers.Base_Power'),
        ),
        migrations.AlterField(
            model_name='power_param',
            name='dice_system',
            field=models.CharField(choices=[('ALL', 'All'), ('HOUSEGAMES15', 'House Games 1.5'), ('PS2', 'New Powers System')], default='PS2', max_length=55),
        ),
    ]
