# Generated by Django 3.2.9 on 2022-01-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0032_auto_20211230_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfieldroll',
            name='relevant_marker',
            field=models.ForeignKey(blank=True, help_text='If not specified, this is the name of the field slugified.', null=True, on_delete=django.db.models.deletion.CASCADE, to='powers.fieldsubstitutionmarker'),
        ),
        migrations.AddField(
            model_name='systemfieldroll',
            name='replacement',
            field=models.CharField(blank=True, help_text="A '$' in this string will be replaced with user input. Defaults to '$' if empty.", max_length=350),
        ),
        migrations.AddField(
            model_name='systemfieldtext',
            name='relevant_marker',
            field=models.ForeignKey(blank=True, help_text='If not specified, this is the name of the field slugified.', null=True, on_delete=django.db.models.deletion.CASCADE, to='powers.fieldsubstitutionmarker'),
        ),
        migrations.AddField(
            model_name='systemfieldtext',
            name='replacement',
            field=models.CharField(blank=True, help_text="A '$' in this string will be replaced with user input. Defaults to '$' if empty.", max_length=350),
        ),
    ]
