# Generated by Django 3.2.9 on 2022-01-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0033_auto_20220102_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawback',
            name='multiple_sub_strategy',
            field=models.CharField(choices=[('AND', "Join using 'and'"), ('OR', "Join using 'or'"), ('ALL', 'Display all seperately')], default='AND', help_text='When a modifier has multiplicity allowed and details, this specifies how the details should be joined before they are subbed.', max_length=55),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='multiple_sub_strategy',
            field=models.CharField(choices=[('AND', "Join using 'and'"), ('OR', "Join using 'or'"), ('ALL', 'Display all seperately')], default='AND', help_text='When a modifier has multiplicity allowed and details, this specifies how the details should be joined before they are subbed.', max_length=55),
        ),
    ]
