# Generated by Django 3.2.9 on 2022-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0034_auto_20220102_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power_system',
            name='system_text',
            field=models.TextField(help_text="((marker1,marker2)) : join markers with 'and', capitalize first.<br>[[marker|default]] : replace marker, or use default if no replacement.<br>[[marker]] : replace marker or blank if no replacement.<br>{{marker}} : replace marker, paragraph breaks between multiple entries.<br>@@marker1,marker2%% : join markers with 'or', no capitalization added."),
        ),
    ]
