# Generated by Django 3.2.9 on 2022-01-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0058_weapon'),
        ('powers', '0036_alter_base_power_system_system_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFieldWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eratta', models.CharField(blank=True, max_length=1000, null=True)),
                ('replacement', models.CharField(blank=True, help_text="A '$' in this string will be replaced with user input. Defaults to '$' if empty.", max_length=350)),
                ('weapon_type', models.CharField(blank=True, choices=[('MELEE', 'Melee Weapon'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', help_text='Provides the following substitutions based on the selected weapon: <br>selected-weapon-name, selected-weapon-type, selected-weapon-bonus-damage, selected-weapon-attack-roll, selected-weapon-attack-roll-difficulty, selected-weapon-attack-text, selected-weapon-range, selected-weapon-errata', max_length=30)),
                ('base_power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.base_power_system')),
                ('relevant_marker', models.ForeignKey(blank=True, help_text='If not specified, this is the name of the field slugified.', null=True, on_delete=django.db.models.deletion.CASCADE, to='powers.fieldsubstitutionmarker')),
            ],
            options={
                'abstract': False,
                'unique_together': {('base_power_system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemFieldWeaponInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eratta', models.CharField(blank=True, max_length=1000, null=True)),
                ('replacement', models.CharField(blank=True, help_text="A '$' in this string will be replaced with user input. Defaults to '$' if empty.", max_length=350)),
                ('base_power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.base_power_system')),
                ('relevant_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.systemfieldweapon')),
                ('relevant_marker', models.ForeignKey(blank=True, help_text='If not specified, this is the name of the field slugified.', null=True, on_delete=django.db.models.deletion.CASCADE, to='powers.fieldsubstitutionmarker')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.weapon')),
            ],
            options={
                'abstract': False,
                'unique_together': {('base_power_system', 'name')},
            },
        ),
    ]
