# Generated by Django 3.2.9 on 2022-02-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0037_systemfieldweapon_systemfieldweaponinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfieldweapon',
            name='weapon_type',
            field=models.CharField(blank=True, choices=[('MELEE', 'Melee'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', help_text='Provides the following substitutions based on the selected weapon: <br>selected-weapon-name, selected-weapon-type, selected-weapon-bonus-damage, selected-weapon-attack-roll, selected-weapon-attack-roll-difficulty, selected-weapon-attack-text, selected-weapon-range, selected-weapon-errata', max_length=30),
        ),
        migrations.CreateModel(
            name='VectorCostCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_credit', models.IntegerField(verbose_name='Gift Credit')),
                ('relevant_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_effect', to='powers.base_power')),
                ('relevant_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_vector', to='powers.base_power')),
            ],
        ),
        migrations.AddField(
            model_name='base_power',
            name='vector_cost_credit',
            field=models.ManyToManyField(through='powers.VectorCostCredit', to='powers.Base_Power'),
        ),
    ]
