# Generated by Django 3.2.9 on 2022-02-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0039_auto_20220205_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfieldweapon',
            name='weapon_type',
            field=models.CharField(blank=True, choices=[('MELEE', 'Melee'), ('UNARMED', 'Unarmed'), ('FIREARM', 'Firearm'), ('THROWN', 'Thrown'), ('PROJECTILE', 'Projectile'), ('OTHER', 'Other')], default='MELEE', help_text='Provides the following substitutions based on the selected weapon: <br>selected-weapon-name, selected-weapon-type, selected-weapon-bonus-damage, selected-weapon-attack-roll, selected-weapon-attack-roll-difficulty, selected-weapon-attack-text, selected-weapon-range, selected-weapon-errata', max_length=30),
        ),
    ]
