# Generated by Django 3.2.9 on 2022-02-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0041_alter_base_power_system_system_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('min_required', models.IntegerField(blank=True, help_text='if specified, the minimum number of required enhancements of this group. For example, informational enhancements or commune enhancements', null=True, verbose_name='Num Enhancements Required')),
                ('seasoned_threshold', models.IntegerField(blank=True, help_text='Requires Seasoned to take this many enhancements of this group', null=True, verbose_name='Seasoned Threshold')),
                ('veteran_threshold', models.IntegerField(blank=True, help_text='Requires Veteran to take this many enhancements of this group', null=True, verbose_name='Veteran Threshold')),
            ],
        ),
        migrations.AddField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_EFFECT', 'Effect')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_EFFECT', 'Effect')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='powers.enhancementgroup'),
        ),
    ]
