# Generated by Django 3.2.9 on 2022-03-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0044_auto_20220309_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfieldweaponinstance',
            name='relevant_power',
            field=models.ForeignKey(default=3997, on_delete=django.db.models.deletion.CASCADE, to='powers.power'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_EFFECT', 'Effect'), ('MOD_ACTIVATION', 'Activation / Targeting')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_EFFECT', 'Effect'), ('MOD_ACTIVATION', 'Activation / Targeting')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='systemfieldweaponinstance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='systemfieldweaponinstance',
            name='base_power_system',
        ),
        migrations.RemoveField(
            model_name='systemfieldweaponinstance',
            name='eratta',
        ),
        migrations.RemoveField(
            model_name='systemfieldweaponinstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='systemfieldweaponinstance',
            name='relevant_marker',
        ),
        migrations.RemoveField(
            model_name='systemfieldweaponinstance',
            name='replacement',
        ),
    ]
