# Generated by Django 3.2.9 on 2022-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0050_auto_20220314_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='drawback_names',
            field=models.JSONField(default=list, verbose_name='Drawback Names'),
        ),
        migrations.AddField(
            model_name='power',
            name='enhancement_names',
            field=models.JSONField(default=list, verbose_name='Enhancement Names'),
        ),
    ]
