# Generated by Django 3.2.9 on 2022-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0053_powersystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='extended_description',
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AddField(
            model_name='power',
            name='gift_summary',
            field=models.TextField(default='', max_length=2500, verbose_name='gift summary'),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_EFFECT', 'Effect'), ('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_GIFT', 'Gift Type')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_EFFECT', 'Effect'), ('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_GIFT', 'Gift Type')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='power',
            name='description',
            field=models.TextField(max_length=2500, verbose_name='visual description'),
        ),
    ]
