# Generated by Django 3.2.9 on 2022-03-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0064_auto_20220326_1840'),
        ('powers', '0054_auto_20220320_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactpower',
            name='relevant_power_full',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='powers.power_full'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base_power',
            name='crafting_type',
            field=models.CharField(choices=[('NONCRAFTABLE', 'Not craftable'), ('ARTIFACT_CRAFTING', 'Artifact Crafting'), ('CONSUMABLE_CRAFTING', 'Consumable Crafting')], default='NONCRAFTABLE', max_length=45),
        ),
        migrations.AddField(
            model_name='power',
            name='warnings',
            field=models.JSONField(default=list, verbose_name='Gift Warnings'),
        ),
        migrations.AddField(
            model_name='power_full',
            name='crafting_type',
            field=models.CharField(choices=[('NONCRAFTABLE', 'Not craftable'), ('ARTIFACT_CRAFTING', 'Artifact Crafting'), ('CONSUMABLE_CRAFTING', 'Consumable Crafting')], default='NONCRAFTABLE', max_length=45),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_EFFECT', 'Effect'), ('MOD_GIFT', 'Gift Type'), ('MOD_ACTIVATION', 'Activation / Targeting')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_EFFECT', 'Effect'), ('MOD_GIFT', 'Gift Type'), ('MOD_ACTIVATION', 'Activation / Targeting')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='artifactpower',
            unique_together={('relevant_artifact', 'relevant_power_full')},
        ),
        migrations.RemoveField(
            model_name='artifactpower',
            name='detail',
        ),
    ]
