# Generated by Django 3.2.9 on 2022-03-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0065_alter_artifact_location'),
        ('powers', '0055_auto_20220326_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power',
            name='crafting_type',
            field=models.CharField(choices=[('NONCRAFTABLE', 'Not craftable'), ('SIGNATURE ITEM', 'Signature Item'), ('ARTIFACT_CRAFTING', 'Artifact Crafting'), ('CONSUMABLE_CRAFTING', 'Consumable Crafting')], default='NONCRAFTABLE', max_length=45),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_GIFT', 'Gift Type'), ('MOD_EFFECT', 'Effect')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_GIFT', 'Gift Type'), ('MOD_EFFECT', 'Effect')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='power_full',
            name='crafting_type',
            field=models.CharField(choices=[('NONCRAFTABLE', 'Not craftable'), ('SIGNATURE ITEM', 'Signature Item'), ('ARTIFACT_CRAFTING', 'Artifact Crafting'), ('CONSUMABLE_CRAFTING', 'Consumable Crafting')], default='NONCRAFTABLE', max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='artifactpower',
            unique_together={('relevant_artifact', 'relevant_power')},
        ),
        migrations.CreateModel(
            name='ArtifactPowerFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.artifact')),
                ('relevant_power_full', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.power_full')),
            ],
            options={
                'unique_together': {('relevant_artifact', 'relevant_power_full')},
            },
        ),
        migrations.RemoveField(
            model_name='artifactpower',
            name='relevant_power_full',
        ),
        migrations.AddField(
            model_name='power_full',
            name='artifacts',
            field=models.ManyToManyField(through='powers.ArtifactPowerFull', to='characters.Artifact'),
        ),
    ]
