# Generated by Django 3.2.9 on 2022-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0065_auto_20220408_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_EFFECT', 'Effect'), ('MOD_GIFT', 'Gift Type')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_EFFECT', 'Effect'), ('MOD_GIFT', 'Gift Type')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='power',
            name='creation_reason',
            field=models.CharField(choices=[('NEW', 'New'), ('IMPROVEMENT', 'Improvement'), ('REVISION', 'Revision'), ('ADJUSTMENT', 'Adjustment'), ('MAJOR REVISION', 'Major Revision'), ('UPGRADEPS2', 'Upgrade')], max_length=25),
        ),
    ]
