# Generated by Django 3.2.9 on 2022-05-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0068_auto_20220421_2049'),
        ('powers', '0066_auto_20220421_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_EFFECT', 'Effect')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_ACTIVATION', 'Activation / Targeting'), ('MOD_EFFECT', 'Effect')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.CreateModel(
            name='PowerActiveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('relevant_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.artifact')),
                ('relevant_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.power')),
            ],
        ),
        migrations.AddIndex(
            model_name='poweractivestatus',
            index=models.Index(fields=['relevant_power', 'relevant_artifact'], name='powers_powe_relevan_6f773b_idx'),
        ),
    ]
