# Generated by Django 3.2.9 on 2022-05-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0068_auto_20220503_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorcostcredit',
            name='relevant_modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_modality', to='powers.base_power'),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_EFFECT', 'Effect'), ('MOD_ACTIVATION', 'Activation / Targeting')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='category',
            field=models.CharField(choices=[('MOD_GIFT', 'Gift Type'), ('MOD_EFFECT', 'Effect'), ('MOD_ACTIVATION', 'Activation / Targeting')], default='MOD_EFFECT', help_text='For filtering on create gift page', max_length=30),
        ),
        migrations.AlterField(
            model_name='vectorcostcredit',
            name='gift_credit',
            field=models.IntegerField(help_text='The cost of any Gift using this combination of Effect and Vector is reduced by this amount. Modality optional.', verbose_name='Gift Credit'),
        ),
    ]
