# Generated by Django 3.2.9 on 2022-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0071_auto_20220514_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersystem',
            name='cache_key',
            field=models.CharField(default='user', max_length=220),
        ),
    ]
