# Generated by Django 3.2.15 on 2022-10-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0073_auto_20220920_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_full',
            name='stock_order',
            field=models.IntegerField(default=0),
        ),
    ]
