# Generated by Django 3.2.15 on 2023-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0076_alter_base_power_system_system_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_power',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
        migrations.AlterField(
            model_name='drawback',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='required_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
        migrations.AlterField(
            model_name='power',
            name='required_status',
            field=models.CharField(blank=True, choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], max_length=25),
        ),
    ]
