# Generated by Django 3.2.15 on 2023-07-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0099_auto_20230611_1846'),
        ('powers', '0077_auto_20230514_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactpower',
            name='relevant_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.artifact'),
        ),
    ]
