# Generated by Django 3.2.18 on 2023-11-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20231123_1524'),
        ('powers', '0078_alter_artifactpower_relevant_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.privateuserimage')),
                ('relevant_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.power')),
            ],
        ),
        migrations.AddIndex(
            model_name='powerimage',
            index=models.Index(fields=['relevant_power'], name='powers_powe_relevan_404568_idx'),
        ),
        migrations.AddIndex(
            model_name='powerimage',
            index=models.Index(fields=['relevant_image'], name='powers_powe_relevan_98f4e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='powerimage',
            unique_together={('relevant_image', 'relevant_power')},
        ),
    ]
