# Generated by Django 3.2.18 on 2023-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20231123_1524'),
        ('powers', '0079_auto_20231123_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='images',
            field=models.ManyToManyField(through='powers.PowerImage', to='images.PrivateUserImage'),
        ),
    ]
