# Generated by Django 4.2.9 on 2025-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0080_power_images'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='power',
            index=models.Index(fields=['parent_power'], name='powers_powe_parent__8951ac_idx'),
        ),
        migrations.AddIndex(
            model_name='power',
            index=models.Index(fields=['created_by'], name='powers_powe_created_70ac2f_idx'),
        ),
        migrations.AddIndex(
            model_name='power_full',
            index=models.Index(fields=['character'], name='powers_powe_charact_7298ba_idx'),
        ),
        migrations.AddIndex(
            model_name='power_full',
            index=models.Index(fields=['latest_rev'], name='powers_powe_latest__20dda8_idx'),
        ),
    ]
