# Generated by Django 4.2.9 on 2025-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0081_power_powers_powe_parent__8951ac_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artifactpower',
            index=models.Index(fields=['relevant_power'], name='powers_arti_relevan_5436e6_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactpower',
            index=models.Index(fields=['relevant_artifact'], name='powers_arti_relevan_156faf_idx'),
        ),
    ]
