# Generated by Django 2.2.13 on 2021-03-28 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0023_auto_20210312_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(blank=True, max_length=74000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='date last edited')),
                ('is_downtime', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('contains_spoilers', models.BooleanField(default=True)),
                ('game_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game_Attendance')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_downtime', False)), fields=('game_attendance',), name='one_journal_per_game'),
        ),
    ]
