# Generated by Django 2.2.13 on 2021-03-19 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0023_auto_20210312_1743'),
        ('characters', '0028_auto_20210317_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(blank=True, max_length=74000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='date last edited')),
                ('is_downtime', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
    ]
