# Generated by Django 2.2.13 on 2021-04-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20210317_0407'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='experience_reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.ExperienceReward'),
        ),
    ]
