# Generated by Django 2.2.13 on 2021-04-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20210317_0407'),
        ('journals', '0002_journal_experience_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(blank=True, max_length=74000, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.AddConstraint(
            model_name='journalcover',
            constraint=models.UniqueConstraint(fields=('character',), name='one_cover_per_contractor'),
        ),
    ]
