# Generated by Django 2.2.13 on 2021-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20210406_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
