# Generated by Django 3.2.15 on 2023-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journal_is_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
