# Generated by Django 4.2.9 on 2025-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_journal_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['game_attendance'], name='journals_jo_game_at_3114c5_idx'),
        ),
    ]
