# Generated by Django 3.2.18 on 2023-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouncedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=900)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
