# Generated by Django 2.2.12 on 2020-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170521_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmed_agreements',
            field=models.BooleanField(default=False),
        ),
    ]
