# Generated by Django 2.2.12 on 2020-07-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_confirmed_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_confirmed_agreements',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
