# Generated by Django 2.2.13 on 2021-01-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_date_confirmed_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gm_prefix',
            field=models.CharField(blank=True, choices=[('SPECTATOR', 'Spectator'), ('PILLOWY', 'Pillowy'), ('BENEVOLENT', 'Benevolent'), ('JUST', 'Just'), ('SADISTIC', 'Sadistic'), ('CRUEL', 'Cruel')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gm_suffix',
            field=models.CharField(choices=[('SPECTATOR', 'Spectator'), ('MANAGER', 'Manager'), ('BOSS', 'Boss'), ('RULER', 'Ruler'), ('GOD', 'God')], default='SPECTATOR', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='player_prefix',
            field=models.CharField(choices=[('UNTESTED', 'Untested'), ('SHELTERED', 'Sheltered'), ('UNLUCKY', 'Unlucky'), ('RESOURCEFUL', 'Resourceful'), ('DEVIOUS', 'Devious'), ('TORTURED', 'Tortured'), ('CALCULATING', 'Calculating'), ('INGENIOUS', 'Ingenious')], default='UNTESTED', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='player_suffix',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
    ]
