# Generated by Django 2.2.13 on 2021-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210127_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gm_prefix',
            field=models.CharField(blank=True, choices=[('PILLOWY', 'Pillow'), ('BENEVOLENT', 'Benevolent'), ('JUST', 'Just'), ('SADISTIC', 'Sadistic'), ('CRUEL', 'Cruel')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='player_suffix',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('ADEPT', 'Adept'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='NEWBIE', max_length=25),
        ),
    ]
