# Generated by Django 2.2.13 on 2021-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210128_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gm_prefix',
            field=models.CharField(blank=True, choices=[('PILLOW', 'Pillow'), ('BENEVOLENT', 'Benevolent'), ('JUST', 'Just'), ('SADISTIC', 'Sadistic'), ('CRUEL', 'Cruel')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gm_suffix',
            field=models.CharField(choices=[('SPECTATOR', 'Spectator'), ('REFEREE', 'Referee'), ('BOSS', 'Boss'), ('RULER', 'Ruler'), ('GOD', 'God')], default='SPECTATOR', max_length=25),
        ),
    ]
