# Generated by Django 2.2.13 on 2021-04-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210204_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_set_adult_content',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
