# Generated by Django 2.2.13 on 2021-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210429_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_games_gmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gm_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gm_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gm_victories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_golden_ratios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
