# Generated by Django 2.2.13 on 2021-09-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210517_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_contractors_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_deadly_player_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gmed_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gmed_contractors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gmed_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_played_ringers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_player_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_player_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_player_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_player_survivals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_player_victories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gm_suffix',
            field=models.CharField(choices=[('SPECTATOR', 'Spectator'), ('REFEREE', 'Referee'), ('BOSS', 'Boss'), ('RULER', 'Ruler'), ('GOD', 'God'), ('HARBINGER', 'Harbinger'), ('MIDDLE_MANAGEMENT', 'Middle Management')], default='SPECTATOR', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='player_suffix',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('ADEPT', 'Adept'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran'), ('SEASONED', 'Seasoned'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster')], default='NEWBIE', max_length=25),
        ),
    ]
