# Generated by Django 2.2.13 on 2021-09-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_update_stats_migration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_games_gmed'], name='profiles_pr_num_gam_e86cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_gm_kills'], name='profiles_pr_num_gm__bdd9af_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_gmed_players'], name='profiles_pr_num_gme_8805e5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_player_games'], name='profiles_pr_num_pla_e76525_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_played_ringers'], name='profiles_pr_num_pla_7593ec_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_player_survivals'], name='profiles_pr_num_pla_1c634d_idx'),
        ),
    ]
