# Generated by Django 2.2.13 on 2021-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210904_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='player_suffix',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('ADEPT', 'Adept'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran'), ('SEASONED', 'Operative'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster')], default='NEWBIE', max_length=25),
        ),
    ]
