# Generated by Django 3.2.9 on 2021-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_able_to_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ps2_user',
            field=models.BooleanField(default=False),
        ),
    ]
