# Generated by Django 3.2.9 on 2022-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_ps2_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='early_access_user',
            field=models.BooleanField(default=False),
        ),
    ]
