# Generated by Django 3.2.9 on 2022-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_moves_gmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['num_moves_gmed'], name='profiles_pr_num_mov_4f2493_idx'),
        ),
    ]
