# Generated by Django 3.2.15 on 2022-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20220716_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_invitations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='direct_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_contracts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='site_announcements',
            field=models.BooleanField(default=True),
        ),
    ]
