# Generated by Django 3.2.15 on 2022-10-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20221002_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_games_gmed_novice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gm_kills_novice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gm_losses_novice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_gm_victories_novice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_player_games_novice',
            field=models.IntegerField(default=0),
        ),
    ]
