# Generated by Django 3.2.15 on 2022-10-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20221006_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gm_suffix',
            field=models.CharField(choices=[('SPECTATOR', 'Spectator'), ('REFEREE', 'Referee'), ('BOSS', 'Boss'), ('RULER', 'Ruler'), ('GOD', 'God'), ('HARBINGER', 'Harbinger'), ('MIDDLE_MANAGEMENT', 'Manager')], default='SPECTATOR', max_length=25),
        ),
    ]
