# Generated by Django 3.2.15 on 2022-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_profile_gm_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_updates',
            field=models.BooleanField(default=True),
        ),
    ]
