# Generated by Django 3.2.15 on 2023-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_mark_all_messages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_fake_ads',
            field=models.BooleanField(default=False),
        ),
    ]
