# Generated by Django 3.2.15 on 2023-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_profile_hide_fake_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gm_suffix',
            field=models.CharField(choices=[('SPECTATOR', 'Spectator'), ('REFEREE', 'Referee'), ('BOSS', 'Boss'), ('RULER', 'Ruler'), ('GOD', 'God'), ('HARBINGER', 'Harbinger'), ('MIDDLE_MANAGEMENT', 'Manager'), ('PSYCHO', 'Psycho')], default='SPECTATOR', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='player_suffix',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('ADEPT', 'Adept'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran'), ('SEASONED', 'Operative'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('LEGEND', 'Legend')], default='NEWBIE', max_length=25),
        ),
    ]
