# Generated by Django 3.2.15 on 2023-09-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20230831_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exchange_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='exchange_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='exchange_credits',
            field=models.IntegerField(default=0),
        ),
    ]
