# Generated by Django 3.2.20 on 2024-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20230906_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_site_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
