# Generated by Django 3.2.20 on 2024-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_profile_is_site_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_edit_guidebook',
            field=models.BooleanField(default=False),
        ),
    ]
