# Generated by Django 3.2.20 on 2024-05-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_profile_can_edit_guidebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ks_reward_level',
            field=models.CharField(choices=[('KS_NONE', 'None'), ('KS_NEWBIE', 'Newbie'), ('KS_NOVICE', 'Novice'), ('KS_SEASONED', 'Seasoned'), ('KS_PROFESSIONAL', 'Professional'), ('KS_VETERAN', 'Veteran'), ('KS_HARBINGER', 'Harbinger'), ('KS_POWERS', 'Powers That Be')], default='KS_NONE', max_length=50),
        ),
    ]
