# Generated by Django 2.2.12 on 2020-05-29 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0002_auto_20200529_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_declined', models.BooleanField(default=False)),
                ('invited_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cells.CellMembership')),
                ('relevant_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cells.Cell')),
            ],
            options={
                'unique_together': {('invited_player', 'relevant_cell')},
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='invitations',
            field=models.ManyToManyField(related_name='cell_invites', through='cells.CellInvite', to=settings.AUTH_USER_MODEL),
        ),
    ]
