# Generated by Django 2.2.13 on 2021-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='allow_self_invites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cell',
            name='cell_sell',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='community_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='house_rules',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='is_listed_publicly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cell',
            name='setting_create_char_info',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='setting_sheet_blurb',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='cell',
            name='setting_summary',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='setting_description',
            field=models.TextField(blank=True, max_length=70000, null=True),
        ),
        migrations.AlterField(
            model_name='worldevent',
            name='event_description',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='worldevent',
            name='headline',
            field=models.CharField(max_length=1000),
        ),
    ]
