# Generated by Django 2.2.13 on 2021-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_auto_20210504_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='are_contractors_portable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='house_rules',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
