# Generated by Django 2.2.12 on 2020-05-29 19:06

import cells.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_auto_20200529_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='invite_link_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='invite_link_secret_key',
            field=models.CharField(default=cells.models.random_string, max_length=7),
        ),
    ]
