# Generated by Django 2.2.13 on 2021-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_auto_20210504_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_community_link_public',
            field=models.BooleanField(default=False),
        ),
    ]
