# Generated by Django 2.2.12 on 2020-05-30 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0005_auto_20200530_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellinvite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
