# Generated by Django 2.2.13 on 2021-05-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0005_cell_is_community_link_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='find_world_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='find world date'),
        ),
    ]
