# Generated by Django 2.2.13 on 2021-05-21 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0007_auto_20210516_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'permissions': (('admin', 'Administrate'), ('manage_memberships', 'Manage Memberships'), ('manage_roles', 'Run Games'), ('post_events', 'Post World Events'), ('manage_member_characters', 'Manage Contractors'), ('edit_world', 'Edit World'), ('manage_games', 'Manage Games'))},
        ),
    ]
