# Generated by Django 3.2.9 on 2021-12-17 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0008_auto_20210521_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('url', models.CharField(max_length=2000)),
                ('send_for_contracts', models.BooleanField(default=True)),
                ('send_for_events', models.BooleanField(default=True)),
                ('send_for_new_members', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hook_creator', to=settings.AUTH_USER_MODEL)),
                ('parent_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_cell', to='cells.cell')),
            ],
        ),
    ]
