# Generated by Django 3.2.9 on 2022-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0011_alter_cell_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='use_golden_ratio',
            field=models.BooleanField(default=True),
        ),
    ]
