# Generated by Django 3.2.9 on 2022-01-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0012_cell_use_golden_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='use_golden_ratio',
            field=models.BooleanField(default=False),
        ),
    ]
