# Generated by Django 3.2.9 on 2022-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0014_cellmembership_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmembership',
            name='date_banned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date banned'),
        ),
        migrations.AddField(
            model_name='cellmembership',
            name='reason_banned',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
