# Generated by Django 3.2.15 on 2023-10-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0015_auto_20220514_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='house_rules',
            field=models.CharField(blank=True, max_length=80000, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='setting_create_char_info',
            field=models.CharField(blank=True, max_length=90000, null=True),
        ),
    ]
