# Generated by Django 3.2.20 on 2024-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0016_auto_20231017_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmembership',
            name='email_contract_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cellmembership',
            name='email_contract_updates',
            field=models.BooleanField(default=True),
        ),
    ]
