# Generated by Django 3.2.20 on 2024-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0018_manual_email_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmembership',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default="1970-01-01 00:00"),
            preserve_default=False,
        ),
    ]
