# Generated by Django 4.2.9 on 2025-11-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0020_manual_last_activity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worldevent',
            index=models.Index(fields=['parent_cell'], name='cells_world_parent__d12683_idx'),
        ),
    ]
