# Generated by Django 4.2.9 on 2025-11-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0021_worldevent_cells_world_parent__d12683_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worldevent',
            index=models.Index(fields=['parent_cell', 'created_date'], name='cells_world_parent__98747e_idx'),
        ),
    ]
