# Generated by Django 3.2.15 on 2023-02-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLastReadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_read', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(max_length=3000)),
                ('content', models.CharField(max_length=6000)),
                ('url', models.CharField(max_length=3000)),
                ('notif_type', models.CharField(choices=[('PLAYGROUP', 'Playgroup'), ('CONTRACT', 'Contract'), ('SCENARIO', 'Scenario'), ('JOURNAL', 'Journal'), ('REWARD', 'Reward'), ('CONTRACTOR', 'Contractor'), ('PROMO', 'Promotional')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_date'], name='notificatio_user_id_34ebb5_idx'),
        ),
    ]
