# Generated by Django 3.2.15 on 2023-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('PLAYGROUP', 'Playgroup'), ('CONTRACT', 'Contract'), ('SCENARIO', 'Scenario'), ('JOURNAL', 'Journal'), ('REWARD', 'Reward'), ('CONTRACTOR', 'Contractor'), ('PROMO', 'Promotional'), ('WORLD', 'World'), ('MESSAGE', 'Message'), ('ARTIFACT', 'Artifact')], max_length=20),
        ),
    ]
