# Generated by Django 3.2.15 on 2023-06-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20230602_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='variety',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_timeline', 'created_date'], name='notificatio_user_id_adb1ed_idx'),
        ),
    ]
