# Generated by Django 4.2.9 on 2025-11-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20230608_1241'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerlastreadtime',
            index=models.Index(fields=['user'], name='notificatio_user_id_b732c1_idx'),
        ),
    ]
