# Generated by Django 4.2.8 on 2025-05-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_postimageset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImageSet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_set',
        ),
    ]
