# Generated by Django 3.2.15 on 2023-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner', models.ImageField(upload_to='')),
                ('headline', models.CharField(max_length=3000)),
                ('subject', models.CharField(max_length=3000)),
                ('content', models.TextField(max_length=20000)),
            ],
        ),
    ]
