# Generated by Django 3.2.15 on 2023-06-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakead',
            name='banner_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fakead',
            name='banner_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
