# Generated by Django 3.2.20 on 2024-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20240426_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakead',
            name='picture_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fakead',
            name='picture_width',
            field=models.IntegerField(default=0),
        ),
    ]
