# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170829_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='suggested_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='ANY', max_length=25),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='summary',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
