# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_character_death'),
        ('games', '0003_auto_20170906_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_attendance',
            name='character_death',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character_Death'),
        ),
    ]
