# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_attendance_character_death'),
        ('games', '0004_auto_20170910_2227'),
    ]

    operations = [
    ]
