# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20171212_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='relevant_power',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_power', to='powers.Power'),
        ),
    ]
