# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20171212_0407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reward',
            unique_together=set([]),
        ),
    ]
