# Generated by Django 2.2.12 on 2020-06-01 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0011_game_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_gm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('ARCHIVED', 'Archived'), ('CANCELED', 'Canceled'), ('VOID', 'Void'), ('RECORDED', 'Recorded')], default=('SCHEDULED', 'Scheduled'), max_length=25),
        ),
    ]
