# Generated by Django 2.2.12 on 2020-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200610_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scenario_notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
