# Generated by Django 2.2.12 on 2020-07-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200711_1900'),
        ('games', '0014_auto_20200615_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gm_experience_reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.ExperienceReward'),
        ),
        migrations.AddField(
            model_name='game_attendance',
            name='experience_reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.ExperienceReward'),
        ),
        migrations.AlterField(
            model_name='game',
            name='required_character_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='ANY', max_length=25),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='suggested_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='ANY', max_length=25),
        ),
    ]
