# Generated by Django 2.2.12 on 2020-07-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200701_1446'),
    ]

    operations = [
    ]
