# Generated by Django 2.2.12 on 2020-07-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200711_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_charan_coin',
            field=models.BooleanField(default=False),
        ),
    ]
