# Generated by Django 2.2.12 on 2020-07-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_reward_is_charan_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='is_charan_coin',
            new_name='is_charon_coin',
        ),
    ]
