# Generated by Django 2.2.12 on 2020-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20200717_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hook',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='game_invite',
            name='invite_text',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
    ]
