# Generated by Django 2.2.13 on 2020-10-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200831_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(max_length=74000),
        ),
    ]
