# Generated by Django 2.2.13 on 2020-12-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20201230_2224'),
        ('games', '0021_auto_20201006_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.AssetDetails'),
        ),
    ]
