# Generated by Django 2.2.13 on 2021-03-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_reward_source_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_attendance',
            name='experience_reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.ExperienceReward'),
        ),
    ]
