# Generated by Django 2.2.13 on 2021-04-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20210312_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_journal',
            field=models.BooleanField(default=False),
        ),
    ]
