# Generated by Django 2.2.13 on 2021-04-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_reward_is_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario_discovery',
            name='is_spoiled',
            field=models.BooleanField(default=True),
        ),
    ]
