# Generated by Django 2.2.13 on 2021-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_scenario_discovery_is_spoiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
