# Generated by Django 2.2.13 on 2021-05-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_game_is_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='required_character_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE_OR_NOVICE', 'Newbie or Novice'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='ANY', max_length=25),
        ),
    ]
