# Generated by Django 2.2.13 on 2021-05-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20210516_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_ringers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='gametime_url',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='invitation_mode',
            field=models.CharField(choices=[('INVITE_ONLY', 'Invited Players Only'), ('WORLD_MEMBERS', 'World Members Only'), ('ANYONE', 'Anyone'), ('CLOSED', 'Closed for RSVPs')], default=('INVITE_ONLY', 'Invited Players Only'), max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='list_in_lfg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='max_rsvp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='hook',
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
    ]
