# Generated by Django 2.2.13 on 2021-05-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20210516_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMedium',
            fields=[
                ('medium', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='Unique URL-Safe Name')),
                ('color', models.CharField(max_length=40, verbose_name='Css Color')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='mediums',
            field=models.ManyToManyField(blank=True, to='games.GameMedium'),
        ),
    ]
