# Generated by Django 2.2.13 on 2021-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20210517_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='invitation_mode',
            field=models.CharField(choices=[('INVITE_ONLY', 'Invited Players Only'), ('WORLD_MEMBERS', 'World Members Only'), ('ANYONE', 'Any Player'), ('CLOSED', 'Closed for RSVPs')], default=('INVITE_ONLY', 'Invited Players Only'), max_length=25),
        ),
    ]
