# Generated by Django 2.2.13 on 2021-05-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20210517_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='allow_ringers',
        ),
    ]
