# Generated by Django 2.2.13 on 2021-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_remove_game_allow_ringers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_ringers',
            field=models.BooleanField(default=False),
        ),
    ]
