# Generated by Django 2.2.13 on 2021-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_auto_20210530_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_new_player_gm_reward',
            field=models.BooleanField(default=False),
        ),
    ]
