# Generated by Django 2.2.13 on 2021-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_reward_is_new_player_gm_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_ported_reward',
            field=models.BooleanField(default=False),
        ),
    ]
