# Generated by Django 2.2.13 on 2021-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_reward_is_ported_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariotag',
            name='unlock_instructions',
            field=models.CharField(default='.', max_length=400),
        ),
    ]
