# Generated by Django 2.2.13 on 2021-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_scenariotag_unlock_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='deadliness_ratio',
            field=models.FloatField(default=0, verbose_name='A denormalization of deaths over victories'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='num_deaths',
            field=models.IntegerField(default=0, verbose_name='Number of deaths caused by this Scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='num_gms_run',
            field=models.IntegerField(default=0, verbose_name='Number of GMs who have run Scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='num_victories',
            field=models.IntegerField(default=0, verbose_name='Number of victories awarded in this Scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='num_words',
            field=models.IntegerField(default=0, verbose_name='Number of Words'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='times_run',
            field=models.IntegerField(default=0, verbose_name='Number of times Scenario has been run'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['times_run'], name='games_scena_times_r_913ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['num_gms_run'], name='games_scena_num_gms_9f6615_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['num_victories'], name='games_scena_num_vic_b0574e_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['num_deaths'], name='games_scena_num_dea_9d2f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['deadliness_ratio'], name='games_scena_deadlin_7be06a_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['creator'], name='games_scena_creator_af8fe6_idx'),
        ),
    ]
