# Generated by Django 2.2.13 on 2021-10-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_scenario_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='relevant_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Scenario'),
        ),
    ]
