# Generated by Django 2.2.13 on 2021-11-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0054_attribute_is_deprecated'),
        ('games', '0041_scenario_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_attendance',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_attendance',
            name='mvp_reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_exp_attendance', to='characters.ExperienceReward'),
        ),
    ]
