# Generated by Django 3.2.9 on 2022-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20211116_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='invitation_mode',
            field=models.CharField(choices=[('INVITE_ONLY', 'Invited Players Only'), ('WORLD_MEMBERS', 'Playgroup Members Only'), ('ANYONE', 'Any Player'), ('CLOSED', 'Closed for RSVPs')], default='INVITE_ONLY', max_length=55),
        ),
    ]
