# Generated by Django 3.2.9 on 2022-07-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0015_auto_20220514_1620'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0073_alter_experiencereward_type'),
        ('games', '0043_alter_game_invitation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('title', models.TextField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True, max_length=50000)),
                ('is_valid', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cells.cell')),
                ('downtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game_attendance')),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('gm_experience_reward', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.experiencereward')),
                ('main_character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.character')),
                ('public_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cells.worldevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['main_character', 'created_date'], name='games_move_main_ch_bb2826_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['main_character', 'downtime'], name='games_move_main_ch_139ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['gm', 'created_date'], name='games_move_gm_id_363809_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['cell', 'created_date'], name='games_move_cell_id_4aa7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['gm_experience_reward'], name='games_move_gm_expe_2a860b_idx'),
        ),
    ]
