# Generated by Django 3.2.15 on 2022-10-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_game_invite_all_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
