# Generated by Django 3.2.15 on 2022-11-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_move_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_gm_reward',
            field=models.BooleanField(default=False),
        ),
    ]
