# Generated by Django 3.2.15 on 2022-11-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0047_reward_is_gm_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioWriteup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=5000, null=True)),
                ('section_forward', models.TextField(blank=True, max_length=74000)),
                ('section_backstory', models.TextField(blank=True, max_length=74000)),
                ('section_intro', models.TextField(blank=True, max_length=74000)),
                ('section_mission', models.TextField(max_length=74000)),
                ('suggested_status', models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('VETERAN', 'Veteran')], default='ANY', max_length=25)),
                ('max_players', models.IntegerField(verbose_name='Suggested Maximum number of players')),
                ('min_players', models.IntegerField(verbose_name='Suggested Minimum number of players')),
                ('is_highlander', models.BooleanField(default=False)),
                ('requires_ringer', models.BooleanField(default=False)),
                ('is_rivalry', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('edited_date', models.DateTimeField(auto_now_add=True, verbose_name='date edited')),
                ('num_words', models.IntegerField(default=0, verbose_name='Number of Words')),
                ('relevant_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.scenario')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='scenariowriteup',
            index=models.Index(fields=['relevant_scenario'], name='games_scena_relevan_c0bfa8_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariowriteup',
            index=models.Index(fields=['writer'], name='games_scena_writer__39c741_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenariowriteup',
            unique_together={('relevant_scenario', 'writer')},
        ),
    ]
