# Generated by Django 3.2.15 on 2022-12-06 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0091_auto_20221206_1422'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0050_scenario_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=130)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('relevant_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.stockworldelement')),
                ('relevant_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='stock_elements',
            field=models.ManyToManyField(blank=True, default=None, through='games.ScenarioElement', to='characters.StockWorldElement'),
        ),
        migrations.AddIndex(
            model_name='scenarioelement',
            index=models.Index(fields=['relevant_scenario', 'designation', 'created_date'], name='games_scena_relevan_1b4073_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioelement',
            index=models.Index(fields=['relevant_scenario', 'created_date'], name='games_scena_relevan_651558_idx'),
        ),
    ]
