# Generated by Django 3.2.15 on 2023-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0055_manual_unlock_public_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='required_character_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE_OR_NOVICE', 'Newbie or Novice'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='ANY', max_length=25),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='suggested_status',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEWBIE', 'Newbie'), ('NOVICE', 'Novice'), ('SEASONED', 'Seasoned'), ('PROFESSIONAL', 'Professional'), ('VETERAN', 'Veteran')], default='ANY', max_length=25),
        ),
    ]
