# Generated by Django 3.2.15 on 2023-09-12 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0100_alter_experiencereward_type'),
        ('games', '0057_manual_ported_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='exchange_information',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='is_on_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenario',
            name='num_times_purchased',
            field=models.IntegerField(default=0, verbose_name='Number of times this Scenario was purchased on the exchange'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='wiki_edit_mode',
            field=models.CharField(choices=[('ALL', 'Anyone spoiled'), ('EXCHANGE', 'Scenario Exchange contributors')], default='ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario_discovery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='scenario_discovery',
            name='reason',
            field=models.CharField(choices=[('PLAYED', 'Played'), ('CREATED', 'Created'), ('SHARED', 'Shared'), ('UNLOCKED', 'Unlocked'), ('PURCHASED', 'Purchased')], max_length=25),
        ),
        migrations.CreateModel(
            name='ScenarioApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITING', 'Awaiting Approval'), ('WITHDRAWN', 'Withdrawn'), ('REMOVED', 'Removed')], default='WAITING', max_length=1000)),
                ('feedback', models.CharField(blank=True, max_length=8000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience_reward', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.experiencereward')),
                ('relevant_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.scenario')),
            ],
        ),
    ]
