# Generated by Django 3.2.15 on 2023-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0058_auto_20230912_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='date_added_to_exchange',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
