# Generated by Django 3.2.15 on 2023-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_scenario_date_added_to_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_questionnaire',
            field=models.BooleanField(default=False),
        ),
    ]
