# Generated by Django 3.2.18 on 2024-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0062_manual_populate_scenario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_MVP',
            field=models.BooleanField(default=False),
        ),
    ]
