# Generated by Django 3.2.20 on 2024-05-02 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0064_manual_mvp_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCreditChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=1000)),
                ('value', models.IntegerField()),
                ('rewarded_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
