# Generated by Django 3.2.20 on 2024-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_manual_ks_rewards_batch_1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangecreditchange',
            index=models.Index(fields=['rewarded_player', 'created_time'], name='games_excha_rewarde_8b6d9f_idx'),
        ),
    ]
