# Generated by Django 3.2.20 on 2024-07-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0068_exchangecreditchange_games_excha_rewarde_8b6d9f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_email_date',
            field=models.DateTimeField(null=True, verbose_name='last_email_date'),
        ),
    ]
