# Generated by Django 3.2.20 on 2024-07-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0069_game_last_email_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_email_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_email_date'),
        ),
    ]
