# Generated by Django 3.2.20 on 2024-07-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0070_alter_game_last_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario_discovery',
            name='sharing_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
