# Generated by Django 3.2.20 on 2024-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0071_scenario_discovery_sharing_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='exclude_from_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
