# Generated by Django 3.2.20 on 2024-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0072_scenario_exclude_from_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariowriteup',
            name='content',
            field=models.TextField(max_length=99000),
        ),
    ]
