# Generated by Django 4.2.9 on 2025-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0073_alter_scenariowriteup_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['cell'], name='games_game_cell_id_e55c28_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['cell', 'end_time'], name='games_game_cell_id_56dae8_idx'),
        ),
    ]
