# Generated by Django 4.2.9 on 2025-08-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0020_manual_last_activity'),
        ('games', '0073_alter_scenariowriteup_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='source_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cells.cell'),
        ),
    ]
