# Generated by Django 4.2.9 on 2025-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0074_game_games_game_cell_id_e55c28_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game_attendance',
            index=models.Index(fields=['attending_character'], name='games_game__attendi_ab6890_idx'),
        ),
        migrations.AddIndex(
            model_name='game_attendance',
            index=models.Index(fields=['relevant_game'], name='games_game__relevan_289beb_idx'),
        ),
    ]
