# Generated by Django 4.2.9 on 2025-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0075_game_attendance_games_game__attendi_ab6890_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game_invite',
            index=models.Index(fields=['invited_player'], name='games_game__invited_ae38a5_idx'),
        ),
        migrations.AddIndex(
            model_name='game_invite',
            index=models.Index(fields=['relevant_game'], name='games_game__relevan_d20129_idx'),
        ),
    ]
