# Generated by Django 4.2.9 on 2025-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0076_game_invite_games_game__invited_ae38a5_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['relevant_game'], name='games_rewar_relevan_9a1bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['rewarded_character'], name='games_rewar_rewarde_1473a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['relevant_power'], name='games_rewar_relevan_c09ca8_idx'),
        ),
    ]
