# Generated by Django 4.2.9 on 2025-11-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0075_manual_reward_in_cell'),
        ('games', '0077_reward_games_rewar_relevan_9a1bd8_idx_and_more'),
    ]

    operations = [
    ]
