# Generated by Django 3.2.20 on 2024-02-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('OBSCENE', 'Obscene or explicit content'), ('DOX', 'Sharing personal information'), ('HARASSMENT', 'Abuse or harassment'), ('ADVERTISING', 'Unsolicited advertising or sales'), ('SPAM', 'Spam'), ('OTHER', 'Other (specify below)')], max_length=50)),
                ('extended_reason', models.TextField(blank=True, max_length=6000)),
                ('url', models.CharField(max_length=3000)),
                ('content_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('moderation_date', models.DateTimeField(blank=True)),
                ('moderation_action', models.CharField(blank=True, choices=[('OBSCENE', 'Obscene or explicit content'), ('DOX', 'Sharing personal information'), ('HARASSMENT', 'Abuse or harassment'), ('ADVERTISING', 'Unsolicited advertising or sales'), ('SPAM', 'Spam'), ('OTHER', 'Other (specify below)')], max_length=50)),
                ('moderator_feedback', models.TextField(blank=True, max_length=6000)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderating_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderating_user', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_date'], name='reporting_r_created_5a2788_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', 'created_date'], name='reporting_r_reporte_588f84_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', 'moderation_action'], name='reporting_r_reporte_79cf8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporting_user', 'url')},
        ),
    ]
