# Generated by Django 3.2.20 on 2024-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_report_moderation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='moderation_action',
            field=models.CharField(choices=[('DISMISSED', 'No Action'), ('WARNING', 'Warned'), ('BAN', 'Banned')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['moderation_date', 'url'], name='reporting_r_moderat_0e019b_idx'),
        ),
    ]
