# Generated by Django 3.2.9 on 2022-03-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('powers', '0055_auto_20220326_1840'),
        ('games', '0043_alter_game_invitation_mode'),
        ('characters', '0064_auto_20220326_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_free', models.PositiveIntegerField(default=0)),
                ('is_refundable', models.BooleanField(default=False)),
                ('relevant_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='CraftingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pre_imbue', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=1500, null=True)),
                ('artifacts', models.ManyToManyField(through='crafting.CraftedArtifact', to='characters.Artifact')),
                ('relevant_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game_attendance')),
                ('relevant_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('relevant_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.power')),
                ('relevant_power_full', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.power_full')),
            ],
        ),
        migrations.AddField(
            model_name='craftedartifact',
            name='relevant_crafting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.craftingevent'),
        ),
        migrations.AddIndex(
            model_name='craftingevent',
            index=models.Index(fields=['relevant_power_full'], name='crafting_cr_relevan_3f4126_idx'),
        ),
        migrations.AddIndex(
            model_name='craftingevent',
            index=models.Index(fields=['relevant_attendance'], name='crafting_cr_relevan_0cd81e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='craftingevent',
            unique_together={('relevant_attendance', 'relevant_power_full')},
        ),
        migrations.AddIndex(
            model_name='craftedartifact',
            index=models.Index(fields=['quantity_free'], name='crafting_cr_quantit_3785db_idx'),
        ),
        migrations.AddIndex(
            model_name='craftedartifact',
            index=models.Index(fields=['is_refundable'], name='crafting_cr_is_refu_be76d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='craftedartifact',
            unique_together={('relevant_artifact', 'relevant_crafting')},
        ),
    ]
