# Generated by Django 3.2.9 on 2022-04-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0068_auto_20220421_2049'),
        ('crafting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftingevent',
            name='is_pre_imbue',
        ),
        migrations.AddField(
            model_name='craftingevent',
            name='total_exp_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='craftedartifact',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='craftedartifact',
            name='relevant_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.artifact'),
        ),
        migrations.AddIndex(
            model_name='craftingevent',
            index=models.Index(fields=['relevant_character'], name='crafting_cr_relevan_32ad33_idx'),
        ),
    ]
